### ISSUE TITLE
[TalesWeaver] Screen glitching using the experimental release

### ISSUE THREAD

**Issue by mattlyp** [narzoul/DDrawCompat#72] opened 2020-06-20 15:45 UTC
Currently I am using the experimental release of DDrawCompat, the result is absolutely amazing, just like playing in windows 7. Comparing to the 2016ish release, the 2016 helps a little bit but still feels laggy on windows 10. But I find out that using the experimental release will having the screen glitching problem while the 2016 won't. When I tabbed out and tabbed back into the game, the glitch will disappear but still happening randomly. 
![Image 325](https://user-images.githubusercontent.com/8560831/85205722-b5140d80-b34f-11ea-958d-1bec6b16d216.jpg)
![Image 326](https://user-images.githubusercontent.com/8560831/85205725-b7766780-b34f-11ea-9df3-ecfb455a18ab.jpg)

Here is the log which seems to be normal. 
0c6c 23:32:21.075 Process path: D:\TWclient\InphaseNXD.EXE
0c6c 23:32:21.075 Environment variable __COMPAT_LAYER = "DisableDXMaximizedWindowedMode RunAsAdmin 16BitColor WinXPSp3"
0c6c 23:32:21.075 Loading DDrawCompat statically from D:\TWclient\DDRAW.dll
0c6c 23:32:21.077 DDrawCompat loaded successfully
0c6c 23:32:21.177 Installing display mode hooks
0c6c 23:32:21.182 Installing registry hooks
0c6c 23:32:21.182 Installing Direct3D driver hooks
0c6c 23:32:21.182 Installing Win32 hooks
0c6c 23:32:21.212 Hooking user mode display driver: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_ae0a6307e8a28cc4\nvldumd.dll
0c6c 23:32:21.295 Installing DirectDraw hooks
0c6c 23:32:21.296 Installing Direct3D hooks
0c6c 23:32:21.299 Installing GDI hooks
0c6c 23:32:21.321 Finished installing hooks

**Comment by narzoul** [comment] 2020-06-20 20:16
Well, I finally figured out how to run this game (I don't speak Japanese), and I can reproduce the issue. Next time, please at least mention the game title so I don't have to search around for it.

I checked the older experimental releases, and it looks like the last working version was released on 7 June 2019 (0f88271668b68778c317c0b5da02ee40a209e271) The next release from 3 August 2019 (7068d282ff6bcd141700b3d34ee32def61b51c6b) was already broken, so the breaking change must be somewhere between those two. I will look into it some more.

Meanwhile, here is the last working version reuploaded for you: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/4808495/ddraw.zip)
Please confirm if it's working as expected.

**Comment by narzoul** [comment] 2020-06-21 21:19
Found the bug. Now it's fixed in the latest experimental release too. Thanks for the report!

**Closed by narzoul** 2020-06-21 21:19 UTC
