### ISSUE TITLE
Option for DONT keep aspect ratio

### ISSUE THREAD

**Issue by De-M-oN** [narzoul/DDrawCompat#194] opened 2023-01-25 00:13 UTC
It works really amazing for Road Rash, but WHY it is not possible to discard the aspect ratio?
I have a 16:10 monitor so the stretching would be quite minimal and I want it stretched to fullscreen..
Now also the video capture would record in 2560x1600 but with inserted black bars into the video.
Please allow stretching.

**Comment by narzoul** [comment] 2023-01-25 00:17
Duplicate of https://github.com/narzoul/DDrawCompat/issues/157. I'll add an option in the next release.

**Closed by narzoul** 2023-01-25 00:17 UTC
