### ISSUE TITLE
Forcing 24-bit zbuffer results in black screen

### ISSUE THREAD

**Issue by PrgmrAtHrt** [narzoul/DDrawCompat#259] opened 2023-11-18 06:00 UTC
Despite DDrawCompat reporting that my device supports 24-bit zbuffer, I am getting a black screen when forcing it.

![24 bit zbuffer issue](https://github.com/narzoul/DDrawCompat/assets/38510213/94dfbc03-edf5-4a4e-9eff-dc8b7ef88ad0)

[DDrawCompat-SWEP1RCR.zip](https://github.com/narzoul/DDrawCompat/files/13399157/DDrawCompat-SWEP1RCR.zip)

**Comment by narzoul** [comment] 2023-11-18 11:31
I think the problem is not with depth buffer support, but that this game requires CPU access to the depth buffer, so a conversion is needed from the forced format to 16-bit that the CPU expects. This only works correctly on my AMD GPU. I tried the shader approach too, but that doesn't work on either AMD or NVIDIA.

ForceD3D9On12 should, if supported by your driver. It might not be:
https://www.intel.com/content/www/us/en/support/articles/000057520/graphics.html
But it introduces stuttering in movies.

Is there a particular reason for forcing a higher precision depth buffer in this game? I didn't see any Z-fighting issues, but I didn't test it much.

The only possible alternative I can see is doing the depth conversion on the CPU, but the performance hit might be significant.

**Comment by PrgmrAtHrt** [comment] 2023-11-18 18:20
I am attempting to force it because I do indeed have z-fighting issues.

**Comment by narzoul** [comment] 2023-11-19 12:37
What's your CPU model exactly? Is this an NVIDIA Optimus laptop or a desktop PC? Can you try updating your Intel GPU driver?

I find it strange that your GPU doesn't expose any depth texture FOURCCs like INTZ, DF16 or DF24. According to this page all should be supported, the last two even on older GPUs:
https://aras-p.info/texts/D3D9GPUHacks.html#depth

It's also possible that these formats are supported, but not exposed by the driver for DirectX 7. I made a quick hack to check what formats would be returned for DX9:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/13403152/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/13403157/diff.txt) compared to v0.5.1)

Please upload at least info level logs with this. It doesn't matter if it crashes or doesn't work properly, I'm only interested in the supported resource formats list.

**Comment by PrgmrAtHrt** [comment] 2023-11-19 15:53
I'm using a laptop. My cpu is an Intel i5-3320m. I'm using integrated graphics. There are no updates as this chip has been sunsetted.

[DDrawCompat-SWEP1RCR.log](https://github.com/narzoul/DDrawCompat/files/13403702/DDrawCompat-SWEP1RCR.log)

**Comment by narzoul** [comment] 2023-11-20 22:38
Ok, so those formats are supported under DX9 at least. I can try to (ab)use that. Here's an experimental version, I didn't have much time to test but it seems to work on my AMD GPU that supports the same depth texture formats:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/13419997/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/13419998/diff.txt) compared to v0.5.1)

**Comment by PrgmrAtHrt** [comment] 2023-11-21 16:46
Works beautifully! Well done!

**Comment by narzoul** [comment] 2024-04-21 21:44
Fixed in v0.5.2.

**Closed by narzoul** 2024-04-21 21:44 UTC
