### ISSUE TITLE
Conquest Frontier Wars crashes with v0.3.0

### ISSUE THREAD

**Issue by elishacloud** [narzoul/DDrawCompat#96] opened 2021-04-29 01:16 UTC
The wrapper crashes with v0.3.0 (and v0.2.1), but works fine with v0.2.0 on [Conquest Frontier Wars](https://www.gog.com/game/conquest_frontier_wars), I am using the GOG version.  It crashes after restarting a game or leaving a game.  I tried with the debug version and the game won't even play at all.  The release version with debug logs actually works better than the regular release version and is much harder to make the game crash (sorry for the large log files here).

Debug build crashes on launch:
[DDrawCompat-Conquest-Debug.zip](https://github.com/narzoul/DDrawCompat/files/6395739/DDrawCompat-Conquest-Debug.zip)

Release build with debug logs (takes longer to crash the game):
[DDrawCompat-Conquest.zip](https://github.com/narzoul/DDrawCompat/files/6395740/DDrawCompat-Conquest.zip)

**Comment by narzoul** [comment] 2021-05-01 12:01
I'm unable to reproduce the crash with either "restart mission" or "resign", and it's not clear from the logs what goes wrong. Can you check a crash dump?

**Comment by elishacloud** [comment] 2021-05-03 04:07
For some reason no crash dumps are created, the game just seems to exit by itself.  If you use the release build without logs it seems to crash easier.  Here are the steps:

1. Click "Single Player"
2. Select "Campaign"
3. Select "Terran Campaign"
4. Click on the circle to select Mission 1.
5. Click "Start" to start the mission.
6. Once the mission is started, press ESC to bring up the menu and then exit the mission.
7. Once the mission is exited, click on the circle to select Mission 1 again.
8. Click "Start" to start the mission again.
9. Once the mission is started, press ESC to bring up the menu and then exit the mission.
10. If you are using the release build it will typically crash here.  If not, then repeat steps 7 though 9 until crash (exits).

**Comment by narzoul** [comment] 2021-05-04 21:19
Yes, I got it now, thanks. After running it through a debugger, it looks like it's accessing a deleted IDirectDrawClipper interface in updateWindowClipList (DirectDrawClipper.cpp). The Release method's hook should normally remove the deleted instances from g_clipperData, but it looks like it doesn't get invoked (at least not through the vtable) when the parent DirectDraw object is released without explicitly releasing the clipper first. I'll figure out some fix for this for the next release.

Funny, I seem to remember I caught this issue before too. It looks like I forgot to fix it though...

**Comment by narzoul** [comment] 2021-05-16 16:02
Fixed in v0.3.1. Thanks for all the reports!

**Closed by narzoul** 2021-05-16 16:02 UTC
