### ISSUE TITLE
Windows 11 24H2

### ISSUE THREAD

**Issue by Erometal** [narzoul/DDrawCompat#371] opened 2024-10-04 18:39 UTC
I clean installed the latest build of windows 11 (24H2) and tried to play the sims 1 with the ddrawcompat fix and it's always worked on 22h2 and 23h2 but since the 24H2 release it stopped working. The game "loads" but nothing on the taskbar or desktop. So I looked into task manager and found that the sims wasn't under the "apps" list but instead under the "Background processes" list. I have to close it that way to get the program to stop. I've since clean installed windows 11 23H2 "thankfully I have a backup ISO". Your .dll works perfectly fine again. So something to do with 24H2 has twiddled something with directX. I love what you do for the retro gaming scene and I appreciate your work. Hope this information helps!

**Comment by narzoul** [comment] 2024-10-04 18:43
It should already be fixed since v0.5.3. Are you using an older version by chance?

**Comment by Erometal** [comment] 2024-10-04 18:45
I used your latest version. Not 0.5.3

**Comment by narzoul** [comment] 2024-10-04 18:47
I mean, v0.5.4 is also fixed. I just tried it, no issues here with 24H2. If it's not the case for you, please enable LogLevel=debug in DDrawCompat.ini and upload your logs.

**Comment by Erometal** [comment] 2024-10-04 18:49
I'll use my laptop as a test when 24H2 is available to upgrade as I've reinstalled 23h2 back on my desktop but it's running great again. Something to do with 24h2 or the patcher I use? I'm not sure

**Comment by BEENNath58** [comment] 2024-10-06 08:23
I have tested other games on 24H2 today, but they all worked fine

**Comment by Erometal** [comment] 2024-10-06 08:28
Yeah but for this instance it didn't work for me no matter what I tried. With a clean install. So I'm not using 24H2 till Microsoft make it more stable.

**Comment by Erometal** [comment] 2024-10-06 13:04
I can use my laptop as a dummy and install 24H2 on there and see if the same results show up? Then I can send the log file. I don't use the laptop for much anyways

**Comment by narzoul** [comment] 2024-10-06 13:25
Up to you, but I'm pretty sure the issue is already fixed, since it was reported multiple times before and confirmed as fixed by multiple people, including myself. You must have used the wrong version when testing, or whatever patcher you mentioned is causing additional problems with this game, or it's automatically replacing DDrawCompat with an older version or something like that.

There's a tiny chance that there are other issues with DDrawCompat on 24H2 that cause the exact same problem, and that nobody else has encountered it yet, but I think that's less likely.

**Comment by narzoul** [comment] 2024-10-06 16:23
I've updated all the affected releases between v0.3.0 and v0.5.2 (and some of the "debug-previous-builds" under v0.5.3) with new assets (downloads) with a "win11-24h2" suffix. They were patched to be compatible with Windows 11 24H2 by backporting this fix: 89b2a63164dd4775b033fe427eddbb6e94b852cd.
It could be useful for regression testing, even for me.

**Comment by Erometal** [comment] 2024-10-06 17:36
I'm using Faithbeams sims 1 widescreen patcher.

**Comment by narzoul** [comment] 2024-11-03 13:07
I'm going to assume this was already fixed, until it can be proven otherwise with debug logs.

**Closed by narzoul** 2024-11-03 13:07 UTC
