### ISSUE TITLE
The Devil Inside (Inventory problems plus C.T.D.)

### ISSUE THREAD

**Issue by Zerodarkage** [narzoul/DDrawCompat#352] opened 2024-08-27 07:45 UTC
The Devil Inside has some weird issues with the Inventory (In game press F4 to open it):

On the top row (Broken/Bilking graphics):
![image](https://github.com/user-attachments/assets/b6d3a3b6-4477-49dd-a96d-59662614ed3a)

If you examine objects (attic map, etc.):
![image](https://github.com/user-attachments/assets/9302a99f-9664-491f-a846-a0298b01adf0)

Sometimes it works, C.T.D. or gives the execution could not continue error. OK (Close app) or Cancel (Debug app).
Only after you press [ESC] to return to the inventory!

Here is my latest save file, just unzip in the game folder:
[Slot1.zip](https://github.com/user-attachments/files/16758227/Slot1.zip)

Here is the debug log of Devil Inside:
[DDrawCompat-Devil.zip](https://github.com/user-attachments/files/16758270/DDrawCompat-Devil.zip)

Here is the configuration of Devil Inside:
[Config.ini.zip](https://github.com/user-attachments/files/16758415/Config.ini.zip)

Here is the configuration of DDrawCompat:
[DDrawCompatOverlay-Devil.ini.zip](https://github.com/user-attachments/files/16758447/DDrawCompatOverlay-Devil.ini.zip)

Thanks in advance! 

P.S.
This problems happens in older versions!

**Comment by narzoul** [comment] 2024-09-07 23:31
> On the top row (Broken/Bilking graphics):

It looks the same with dgVoodoo, so I don't think the issue is with Direct3D itself. Is there any evidence that it ever looked better on period-correct hardware?

> Sometimes it works, C.T.D. or gives the execution could not continue error. OK (Close app) or Cancel (Debug app).
Only after you press [ESC] to return to the inventory!

I looked at the attic map about a dozen times using your settings, but nothing like that happens for me. If you can get a crash dump with the CrashDump=full setting, along with a debug log preferably, I can look at it.

**Comment by Zerodarkage** [comment] 2024-09-08 02:01
Here:
[](https://drive.google.com/file/d/1MsIInGAcgoskP95a_IebuYO3qARfeohe/view?usp=sharing)

**Comment by Zerodarkage** [comment] 2024-09-08 02:17
> It looks the same with dgVoodoo, so I don't think the issue is with Direct3D itself. Is there any evidence that it ever looked better on period-correct hardware?

I can't find anything... Except this video! Maybe somehow it can help! 
https://www.youtube.com/watch?v=svTSKh0TG_0&ab_channel=retrogamerlucas
P.S.
Overall your DDRAWCOMPAT is way better than DGVODOO2 for this game!

**Comment by narzoul** [comment] 2024-09-08 07:28
The crash is coming from something called xinmm.dll in your game folder. I don't have that file, I guess you installed it from some external patch. It seems to be audio related, I can't help with that unfortunately.

> I can't find anything... Except this video! Maybe somehow it can help!

What am I looking for here? He never seems to open the inventory menu.

**Comment by Zerodarkage** [comment] 2024-09-08 07:36
> The crash is coming from something called xinmm.dll in your game folder. I don't have that file, I guess you installed it from some external patch. It seems to be audio related, I can't help with that unfortunately.
> 
> > I can't find anything... Except this video! Maybe somehow it can help!
> 
> What am I looking for here? He never seems to open the inventory menu.

This file:
https://github.com/YELLO-belly/ogg-winmm/releases

Renamed to xinmm.dll and using a Hex Editor I changed the exe too xinmm.dll (from winmm.dll)
I opened the menu with F4 and closed multiples times! After that I checked multiple items (examine/reading).

**Comment by Zerodarkage** [comment] 2024-09-08 07:55
> > I can't find anything... Except this video! Maybe somehow it can help!
> 
> What am I looking for here? He never seems to open the inventory menu.

Unfortunately this is it. I can't find people playing on actual hardware except this guy! Most of people use virtual machine or Windows XP to 11. Without playing on a real Pentium 3 I think it;s impossible to see how the game really looked like!

**Comment by narzoul** [comment] 2024-09-08 13:05
> This file: https://github.com/YELLO-belly/ogg-winmm/releases
> 
> Renamed to xinmm.dll and using a Hex Editor I changed the exe to xinmm.dll (from winmm.dll) I opened the menu with F4 and closed multiples times! After that I checked multiple items (examine/reading).
> 
> This file I use to fix CD Audio! (Music folder with .ogg of each track)

It still doesn't crash for me even with those files. But anyway, that's not my project and I can't help with audio issues, so you'll have to ask the author of that wrapper to see if it's something that can be fixed.

> Unfortunately this is it. I can't find people playing on actual hardware except this guy! Most of people use virtual machine or Windows XP to 11. Without playing on a real Pentium 3 I think it's impossible to see how the game really looked like!
( I can't remember if this game had this problem with the inventory! I had this game in 2000s)

I just tried it on PCem Windows 98 with Voodoo 3 3000, and it has the exact same graphical glitches in the inventory. So I don't think there is anything to fix, it must have always looked like this.

> Btw, is this normal!? (DDrawCompat creating a log file for the "launcher")

If the launcher loads ddraw.dll (which it does), then of course. You can disable the log by creating a custom ini file for it. Put `LogLevel=none` in `DDrawCompat-Devil Setup.ini`.

I'm closing this issue, as there is nothing to fix in DDrawCompat.

**Closed by narzoul** 2024-09-08 13:05 UTC

**Comment by Zerodarkage** [comment] 2024-09-08 16:56
Ok! Thanks for all your help! I appreciate it!
