### ISSUE TITLE
VertexFixUp black screens when set to CPU on Intel iGPU

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#340] opened 2024-07-12 18:02 UTC
A friend and I ran into this issue while testing the latest update, both laptops use an Intel HD 4000 iGPU.

[DDrawCompat-nfs4.zip](https://github.com/user-attachments/files/16197778/DDrawCompat-nfs4.zip)

**Comment by narzoul** [comment] 2024-07-18 19:28
Is this with the NFS4 modern patch? What other mods or patches, if any? What's in nfs4.ini? Are other NFS games also not working?

At which point does it black screen? Intros, menus, during driving only? What if you start with default DDrawCompat settings and only enable VertexFixup=cpu from the overlay?

Did this patch also have the same issue? https://github.com/narzoul/DDrawCompat/issues/327#issuecomment-2156072823

So far I can't reproduce it, but I don't see what could be special about old Intel iGPUs in this case (which I can't test unfortunately).

**Comment by RavalinoX** [comment] 2024-07-19 20:12
Hello, I am the friend who has this problem on his old laptop.

I have the problem with the SP version of the game without any modifications, and also with Veg's version.

When I switch from GPU to CPU using the overlay in the game, only a quarter of the normal display shows on my monitor. It's like using a magnifier where one quarter is enlarged to fill the whole screen.

What's in the nfs4.ini doesn't make a difference, but this is what it looks like when I use Veg's version:

[NFS4]
Language=english
NoMovies=1
ThrashDriver=DDrawCompat
SingleProcAffinity=1
OwnHeapLimitMb=256
NoErrorReporting=0
Variant=0

The thrash driver used in both versions of the game is the DX7 from Veg's version, but it's the same when I try it with DX6. As soon as VertexFixUp CPU and not GPU is set in the ini, the screen goes black when the game starts, but you can hear the game sound.

**Comment by narzoul** [comment] 2024-07-19 20:19
> When I switch from GPU to CPU using the overlay in the game, only a quarter of the normal display shows on my monitor.

Isn't this because of the ResolutionScale setting? Have you tried with all default DDrawCompat settings, except changing VertexFixup through the overlay?

**Comment by RavalinoX** [comment] 2024-07-19 20:46
Yes, you're right: with the default ini or without an ini file, I can switch to CPU in the game, and the game doesn't get enlarged. However, as soon as I restart the game, the screen goes black again because the overlay saves the setting VertexFixUp = CPU.

I can't test how the fix works in the game after enabling it through the overlay because the game with the default ini has many graphic glitches, and I'm not sure which ini settings in my standard ini fix these glitches.

**Comment by narzoul** [comment] 2024-07-21 09:10
Ok, I found the problem. This should fix it: [ddraw.zip](https://github.com/user-attachments/files/16323613/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/16323615/diff.txt) compared to v0.5.3)

**Comment by RavalinoX** [comment] 2024-07-21 09:51
works now, thank you.

**Comment by narzoul** [comment] 2024-08-25 20:39
Fixed in v0.5.4.

**Closed by narzoul** 2024-08-25 20:39 UTC
