### ISSUE TITLE
Cursor disappear problem in version 0.4.0

### ISSUE THREAD

**Issue by mcdd-workgroup** [narzoul/DDrawCompat#152] opened 2022-10-10 01:06 UTC
I put the dll into RA2 directory, but when I set the screen solution from 800x600 to 1920x1080, the cursor disappear! But in other screen solution my cursor is OK. And in window mode my cursor is OK too(1920x1080). Why it happened?

**Comment by mcdd-workgroup** [comment] 2022-10-10 01:17
There is also a problem that my anti-virus software said that dll is a virus... When I move the dll, the software delete it immidiately.

**Comment by narzoul** [comment] 2022-10-10 18:51
I don't know, the cursor works fine for me at DisplayResolution=desktop. Is that what you're referring to? Please attach your DDrawCompat-game.log file so I can check your exact config. System specs would also be useful.

I can't do much about antivirus software here. You'll have to consult its documentation on how to add an exception or something. Out of curiosity, what are you using? I checked virustotal and nothing suspicious was reported:
https://www.virustotal.com/gui/file/b64c015b8b750b0f58181efd25160680a54ba6de9d3fe19f0d4fb403622bb151

I'm also a little confused, if it's deleted immediately, how did you test the different resolution settings?

**Comment by mcdd-workgroup** [comment] 2022-10-10 23:35
Hi there, when antivirus aoftware delete it, I set the file to the whitelist, and the software doesn't delete it anymore. Well, I'll attach the DDrawCompat-game.log now. If you got something wrong, please tell me. Thx a lot!!!
[DDrawCompat-game.log](https://github.com/narzoul/DDrawCompat/files/9749793/DDrawCompat-game.log)

**Comment by mcdd-workgroup** [comment] 2022-10-10 23:43
My PC's spec is there:
System: Windows 10 Home Edition 21H1
CPU:AMD Athlon X4 730 Quad Core
RAM:8GB
Graphic: nVidia GTX550 Ti

Hope it helps you :)

**Comment by narzoul** [comment] 2022-10-11 20:42
I just realized you may have been talking about changing the resolution in ra2.ini, not in DDrawCompat settings. But even if I change the resolution there, the cursor is fine.

Windows seems to apply some compatibility shims by default, including enabling exclusive fullscreen mode. I think this currently takes precedence over the FullscreenMode=borderless setting of DDrawCompat. The easiest way to get rid of the default Windows compatibility settings is to rename the executable to something other than game.exe, like game2.exe and launch the game through that, if possible (doesn't work in the Origin version of the game).

If exclusive fullscreen mode is the problem (renaming the executable should confirm it), then I remember some other user had problems with some 3rd party software called f.lux making the cursor invisible in another game. If you have something like that running, try closing it too. See this other issue for details: https://github.com/narzoul/DDrawCompat/issues/85

The reason why it might work in non-native resolutions is that DDrawCompat emulates hardware cursors in software when it has to perform display scaling, i.e. when the DisplayResolution setting doesn't match the application's internal resolution. It seems that in your case the software cursor works correctly, only the hardware cursor has issues. There is currently no way to force using software cursors from DDrawCompat, other than changing DisplayResolution to something different than the game's resolution (or vice versa). But I'm hoping one of the above tips will fix the issue without having to add such a setting.

Does the issue also happen when not using DDrawCompat?

**Comment by mcdd-workgroup** [comment] 2022-10-12 00:26
When I use older DDrawCompat, this issue didn't happen. In v0.4.0, every resolution the cursor appear and work fine, except 1920x1080. But curiously, when I exited the game, and moduled **ra2.ini**, let "ScreenWidth=1920""ScreenHeight=1080", and cursor be normal again! Although if I set resolution to other size, next set the resolution to 1920x1080 (**_in the game option, not ra2.ini, the issue happened base on it_**) again, the cursor disappear again......
Um...I will try to enable the "disable fullscreen optimize" option.
I think have no 3rd party software like f.lux(but there are a software called OpenAL in my PC, is it a problem?), so I have no idea of this method, or I uninstall OpenAL?
I am sure that my PC system resolution is 1920x1080, so I don't think it's DisplayResolution setting doesn't match the application's internal resolution.

It's a great work, of course :D

**Comment by narzoul** [comment] 2022-10-12 18:58
Ok, thanks for the details! I can finally reproduce the issue now by changing the resolution setting in the game. I didn't realize there was an in-game setting for it too (didn't think there would be). It's definitely a bug in DDrawCompat then, hopefully I can fix it soon. I'll post a test release here when I do.

**Comment by mcdd-workgroup** [comment] 2022-10-13 00:32
Thanks for your work! Wish you can repair it soon :)

**Comment by narzoul** [comment] 2023-11-13 18:48
Fixed in v0.5.0.

**Closed by narzoul** 2023-11-13 18:48 UTC
