### ISSUE TITLE
Star Wars Rebellion - Cinematics are not displayed

### ISSUE THREAD

**Issue by Sidefix** [narzoul/DDrawCompat#22] opened 2017-10-22 08:35 UTC
Any cutscenes / cinematics for Star Wars - Rebellion [1998] are not displayed, but are heard in the background. 

This only occurs with the most recent 'experimental' version of the binaries.

Of note is that this 'experimental' version is the **ONLY** version so far of this plugin that runs the 3D combat sequences in the game without crashing or visual artefacts. The only problem being that all the colors are screwed up.

**Comment by narzoul** [comment] 2017-10-24 17:36
I don't have this game yet unfortunately, and I couldn't find a demo of it anywhere. I'll look out for it next time it's on sale, probably around December I guess.

**Comment by Tdekas-Kovna** [comment] 2020-03-23 11:09
Hey @narzoul , I will buy you the game on Steam or GoG to help improve it with the Direct Draw DLL. I can say that "DDrawCompat v0.2.1" works well except for when you do a manual space battle. The screen (window with battle) is blank but all the commands and orders are there. I used your DLL to fix Starcraft (as in you actually fixed it) and now I'm trying to get Star Wars Rebellion to work. Send me a message or email me.

**Comment by narzoul** [comment] 2020-03-23 18:54
Thanks, but I do actually have the GOG version already, I just haven't had time to look into this much yet. I don't maintain older versions, so I'll have to look into what's wrong with the experimental release and fix that. Currently the game does not even start up with that. Works fine with v0.2.1 as you said except for space battles (probably a palette issue since I did see an oddly colored ship for a short while...)

I don't know when I'll get around to it, but I'll try to fix it for v0.3.0 eventually. I'm currently busy with other issues.

**Comment by Tdekas-Kovna** [comment] 2020-03-23 23:08
Greetings mate,

That's fine. I really appreciate your efforts to make older games work. If it helps, when you just run the game, without the DLL file, but use -w in the launch command on the shortcut for windowed mode the game works fine. Must be a call within the normal DLL with full screen mode that has an issue. Thanks though for your time and efforts.

Regards,
Bryce
________________________________

**Comment by narzoul** [comment] 2020-04-05 21:45
For those who are using Windows 10 and are only having trouble with graphical issues in the manual battle scenes, here's a possible solution.

Using a hex editor, replace the following hexadecimal bytes in REBEXE.EXE:
`20 6b 08 f2 9f 25 cf 11 a3 1a 00 aa 00 b9 33 56`
with these:
`60 5c 66 a4 73 26 cf 11 a3 1a 00 aa 00 b9 33 56`

These values are actually the GUIDs for IID_IDirect3DRampDevice and IID_IDirect3DRGBDevice, respectively. So this will force the game to use the RGB software emulation device instead of the Ramp software emulation device that it normally uses. It fixes the issue with the GOG version for me, even when just running the game natively without any ddraw wrappers. I think it should work with other versions of the game also.

Like many users suspected on various forums, it seems that this was actually broken during one of the Windows 10 updates. In fact, I tried copying an older version of d3dim.dll into the game folder from both an earlier Windows 10 version and even from my Windows 8 system, and both of them fixed the issue. Though I wouldn't recommend this as a permanent solution, as mixing different system dll versions is likely to create other problems.

Meanwhile, I'm working on fixing this and some other issues in DDrawCompat also. Hopefully it will be ready sometime during the upcoming week.

**Comment by narzoul** [comment] 2020-04-12 15:33
I think I fixed all issues reported in this thread so far (and some others). Please check the latest experimental release.

**Comment by Tdekas-Kovna** [comment] 2020-04-12 15:43
Hey,

I just tested it out. So I should tell you I use Windows 7 64-bit Service Pack 1 and with the experimental release everything seems good EXCEPT when you manually fight a space battle. It now says with this release "Action Not Supported" and then crashes to desktop. Your stable release "DDrawCompat v0.2.1" works EXCEPT for the space battles however in the stable release everything is displayed correctly except inside the "Battle" window as it is just black. So no fighters, no capital ships, no gravity well distortion effects. But everything else is there, so orders, blue squadron, task force 1, arrows to move around, and such.

Regards
Bryce

**Comment by narzoul** [comment] 2020-04-12 16:42
I see. So it looks like the GOG version installed on Win 10 automatically starts in windowed mode (seems to be caused by a modified executable). But with the same installer on Win 7, the game starts up in full-screen mode by default. I managed to get the Win 7 version of the executable from a VM installation for testing on my Win 10 system, and now I get the same issue as you do. But it still works correctly in windowed mode.

Could you check if battles are working for you in windowed mode? You need to start rebexe.exe with the -w command line option.

**Comment by Tdekas-Kovna** [comment] 2020-04-13 02:19
Hey,

So with my GoG version on Windows 7, if I do not use any ddraw.dll file and I run the game in windowed mode everything works but the battles have this error saying "The Pixel Format was invalid as specified" but after you click OK the battle is normal. The experimental release produces the same results.

Regards,
Bryce

**Comment by narzoul** [comment] 2020-04-13 18:58
That is expected. In windowed mode, the game uses the desktop color depth, and in case it's not set to 256 colors, it will produce these errors because it cannot attach a palette to the render target. 

Possible workarounds:
1. Run the game in 256 color mode (right click on the executable, go to Properties -> Compatibility and check "Run in 256 colors")
2. Alternatively, suppress the error messages with the IgnoreMessageBox shim via the Compatibility Administrator, which is what the GOG installer does on Win 10: ![swrcompat](https://user-images.githubusercontent.com/16432233/79148837-7b121280-7dc6-11ea-8e8d-b2c4bfddc09e.png)

I can fix the "Action Not Supported" error for full-screen mode in DDrawCompat, but then the palette is still not correct in the battle window somehow. I'm investigating that further. Meanwhile you can hopefully get the game running correctly in windowed mode.

**Comment by narzoul** [comment] 2020-04-19 18:03
Battles should also work now in full screen mode in the latest experimental release.

I did some further digging and it looks like the ramp device is broken since the Windows 10 October 2018 Update. The last working version of d3dim.dll is 10.0.17134.1 and the first broken one is 10.0.17763.1. If you can get a hold of an older version, that could be an alternative fix when not using a wrapper.

While trying to determine what changed between the two versions, I found that e.g. the reference to d3dramp.dll was removed from d3dim.dll in the 10.0.17763.1 version (yet d3dramp.dll is still present on the system and keeps getting updated version numbers for some reason). This possibly means that support for the ramp device was removed intentionally and is not going to be fixed by future Windows 10 updates.

DDrawCompat now always uses the RGB device instead of the ramp device for software rendering. This results in some visual differences in lighting. The ramp device uses monochromatic (grayscale) lighting with a limited number of different shades per color (16 in this game), while the RGB device implements full colored lights. If this bothers some people, I could try to add a version check for d3dim.dll and still use the ramp device if an older version of d3dim.dll is used. In the long term, this could become a config option.

**Comment by Tdekas-Kovna** [comment] 2020-04-21 11:56
Greetings,

You, my friend, are a godsend. I have tested the "ddraw.dll" from the experimental release and the verdict...... amazing mate. So I tested with NO compatibility, NO Administrative rights. I simply put the "ddraw.dll" in the directory with the main executable and loaded up the game. I went through the startup movie, the main menu, loaded my game, looked at galaxy, tested a space battle, everything was shown and displayed correctly! Amazing effort! How you did it, is just amazing. You have made this game run beautifully, it's such a great game too. And I'm on Windows 7 SP1 64-bit Professional Edition. Thank you for this effort you have done mate! I would like to donate some cash for your time mate but not sure how I could do that, but great effort. Is there a way on GitHub to support you for your efforts?

Regards,
Bryce
________________________________

**Comment by Sidefix** [comment] 2020-04-22 22:35
@narzoul thank you so much for your time, effort and dedication.

I must unfortunately report that I still have two persisting issues:

- An error is displayed (twice in a row; see attached image) when entering manual battles now. **This does not prevent battles from working; dismissing both errors will take me to the battle correctly.**
![image](https://user-images.githubusercontent.com/26040103/80040259-5e7e8480-8502-11ea-9e43-8f75db559af2.png)

- The images of all icons are inverted and their colors also appear to be inverted. **This issue is fixed when running the game in windowed mode.**

Neither of these two issues are game-breaking, and apart from them everything else works like a charm! I cannot thank you enough for breathing new life into not only this, but all games that have been fixed by your work.

**Comment by narzoul** [comment] 2020-04-22 22:52
@Tdekas-Kovna Thanks for the offer, but I'm currently not accepting donations. I'm just glad everything is working fine for you now. :)

@Sidefix Interestingly, I've not had the upside-down icon problem initially, but it started showing up after a while. However, it only happens when I run the game through REBEXE.EXE. If I rename it to something else, it works correctly. I guess it must be some Windows compatibility option (registry entry?) that got messed up somehow. Can you try renaming the executable to see if it fixes the issue for you?

I wrote about the "pixel format was invalid" error message in an earlier comment here. It should only show up in windowed mode. You can try changing the compatibility settings on the executable to start in 256-color mode, or use the IgnoreMessageBox shim as I have shown with the screenshot in my comment above. If the first solution doesn't work and you don't know how to do the second one, I'll provide some more instructions later. What Windows version are you using?

**Comment by Sidefix** [comment] 2020-04-22 23:01
@narzoul 
I edited my above comment to specify that I attempted the 256 bit fix to no avail, buuuut

Your above recommendation to rename the executable fixes BOTH my above issues.
The game now runs with correct colors and icons, fullscreen, and the errors from battle start are gone!

There is a difference in the way the game is rendered now, it appears though. With the proper exe name the game was running in proper 4:3 fullscreen, and now it appears to be in 4:3 but a strange truncated form, with the text appearing much less sharp.
I have encountered this before when attempting other dll fixes on Rebellion, and it appears to be related to the disabling of fullscreen optimizations (I could be very wrong, most of this is way over my head).

Regardless, it's literally just a nitpick at this point.

Thank you again!

**Comment by Sidefix** [comment] 2020-04-22 23:05
Oh and to answer your question, I am running Windows 10 x64 build 1909, with an nvidia graphics card and the latest drivers (445.87 at the time of writing).

**Comment by narzoul** [comment] 2020-04-26 22:10
The upside-down icons seem to be related to the DWM8And16BitMitigation shim being applied. You should see it listed in the __COMPAT_LAYER environment variable in ddraw.log when running the game through REBEXE.EXE.
I think it gets applied when you enable some compatibility settings, like the 256 color mode. It is saved into the registry and won't be deleted when you remove the compatibility settings. You can remove it manually by deleting the REBEXE.EXE entry under these registry paths (proceed with caution if you do this, messing with the registry is dangerous):
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers

Anyway, I added some workarounds for this in DDrawCompat, so it should work correctly now even if you have those registry entries there.

As for the font issues, 256 color modes are not supposed to have font smoothing (ClearType) enabled, so the text looking a bit rough is the expected behavior. With the DWM8And16BitMitigation shim, I think the game was actually running in 32 bit color mode instead of 8 bit, which is probably why it looked nicer.

I hope everything is fixed at this point, so I'm proceeding to close this issue. Feel free to reopen if that's not the case though.

**Closed by narzoul** 2020-04-26 22:10 UTC
