### ISSUE TITLE
Hitman - Codename 47

### ISSUE THREAD

**Issue by IllustriousProsperus** [narzoul/DDrawCompat#390] opened 2024-10-30 21:45 UTC
Tested with the conjunction with the unofficial widescreen patch and extendet distance, the result is good but the texts are illegible (I think caused by the "ResolutionScale = 1920x1080 (Multiplier: -16..16 | 1)" parameter because by default everything appears ok

With DDrawCompat-v0.5.4 **_NO_** settings, ok text

![Screenshot (110)](https://github.com/user-attachments/assets/5672cd42-475b-46cb-95d6-13f9ebd2d16c)

![Screenshot (109)](https://github.com/user-attachments/assets/25dd7425-d9bb-4655-aa0f-b2127f8b5801)

With DDrawCompat-v0.5.4 **_with_** any settings, broken text

![Screenshot (95)](https://github.com/user-attachments/assets/472cff76-1985-4b3b-b10f-7d68ab29835e)

![Screenshot (96)](https://github.com/user-attachments/assets/adb2b7d8-7a32-4f1e-b9c2-6f7ba9055765)

With the widescreen patch the fov H is completely wrong, starting the game in opengl solves everything but the hud is very small but the distance is reduced to a minimum. In 3dfx mode with dgvoodo2...

Totally broken 

![Screenshot (107)](https://github.com/user-attachments/assets/bf43fd33-4de7-456a-b3e1-63405240fbbb)

![Screenshot (108)](https://github.com/user-attachments/assets/b4743bb9-bf6e-43e3-9a61-9bb7b0368cbd)

**Comment by narzoul** [comment] 2024-11-01 13:42
> ResolutionScale = 1920x1080 (Multiplier: -16..16 | 1)

You should read the intro part of the Configuration wiki. You are setting this parameter incorrectly. There is an error log about it even with the default log level. I noticed this in your Pandora's Box logs. Though it shouldn't have to do anything with your current issues.

> With DDrawCompat-v0.5.4 with any settings, broken text

"with any settings" is not very specific. It certainly doesn't happen with just any setting changes. Please always specify all settings that you changed from the default.

Anyway, I figured out that it's caused by antialiasing, and it's easily fixed by using the SpriteDetection=zconst setting. Again, this is explained in the wiki:

> SpriteDetection
> Allows the detection of Direct3D sprites (orthogonally projected texture images) in order to alleviate visual glitches when using the Antialiasing, ResolutionScale or TextureFilter settings. Sprites are often used for displaying menus, HUDs or background images in 3D games.
> 
> Antialiasing is automatically disabled for detected sprites, TextureFilter is replaced by SpriteFilter, and texture coordinates can optionally be fixed up by SpriteTexCoord.

You should always try the various Sprite* and AlternatePixelCenter settings before opening such issues, especially when forcing antialiasing, resolution scaling or texture filtering. These are all known issues with forced "graphics enhancement" settings, documented in the wiki. Even simply searching for keywords like "antialiasing", "resolution scaling" and "texture filtering", you'll find the relevant other settings to try to fix any glitches introduced by them. In most cases you can use the Config overlay to experiment quickly and find the right settings.

> With the widescreen patch the fov H is completely wrong, starting the game in opengl solves everything but the hud is very small but the distance is reduced to a minimum. In 3dfx mode with dgvoodo2...

You didn't specify which widescreen patch you're talking about, and there seem to be a few different variants from a quick google search. I tried the one suggested by PCGamingWiki:
https://www.pcgamingwiki.com/wiki/Hitman:_Codename_47#Widescreen_resolution

I just followed the instructions, except instead of putting dgVoodoo in the scripts directory, I put DDrawCompat there. It works just fine, no issues with FOV. Nor does DDrawCompat do anything with FOV for that matter. Maybe you're using a different mod, which only works properly with OpenGL.

**Closed by narzoul** 2024-11-01 13:42 UTC

**Comment by IllustriousProsperus** [comment] 2024-11-01 18:10
> > ResolutionScale = 1920x1080 (Multiplier: -16..16 | 1)
> 
> You should read the intro part of the Configuration wiki. You are setting this parameter incorrectly. There is an error log about it even with the default log level. I noticed this in your Pandora's Box logs. Though it shouldn't have to do anything with your current issues.
> 
> > With DDrawCompat-v0.5.4 with any settings, broken text
> 
> "with any settings" is not very specific. It certainly doesn't happen with just any setting changes. Please always specify all settings that you changed from the default.
> 
> Anyway, I figured out that it's caused by antialiasing, and it's easily fixed by using the SpriteDetection=zconst setting. Again, this is explained in the wiki:
> 
> > SpriteDetection
> > Allows the detection of Direct3D sprites (orthogonally projected texture images) in order to alleviate visual glitches when using the Antialiasing, ResolutionScale or TextureFilter settings. Sprites are often used for displaying menus, HUDs or background images in 3D games.
> > Antialiasing is automatically disabled for detected sprites, TextureFilter is replaced by SpriteFilter, and texture coordinates can optionally be fixed up by SpriteTexCoord.
> 
> You should always try the various Sprite* and AlternatePixelCenter settings before opening such issues, especially when forcing antialiasing, resolution scaling or texture filtering. These are all known issues with forced "graphics enhancement" settings, documented in the wiki. Even simply searching for keywords like "antialiasing", "resolution scaling" and "texture filtering", you'll find the relevant other settings to try to fix any glitches introduced by them. In most cases you can use the Config overlay to experiment quickly and find the right settings.
> 
> > With the widescreen patch the fov H is completely wrong, starting the game in opengl solves everything but the hud is very small but the distance is reduced to a minimum. In 3dfx mode with dgvoodo2...
> 
> You didn't specify which widescreen patch you're talking about, and there seem to be a few different variants from a quick google search. I tried the one suggested by PCGamingWiki: https://www.pcgamingwiki.com/wiki/Hitman:_Codename_47#Widescreen_resolution
> 
> I just followed the instructions, except instead of putting dgVoodoo in the scripts directory, I put DDrawCompat there. It works just fine, no issues with FOV. Nor does DDrawCompat do anything with FOV for that matter. Maybe you're using a different mod, which only works properly with OpenGL.


I made a mess with the configuration files, I put everything in default. The parameters that create the black lines and unreadable text are the following strings

"ResolutionScale = 1920x1080 (Multiplier: -16..16 | 1)" and "Antialiasing = msaa8x", problem resolved!
