### ISSUE TITLE
Better release cycle

### ISSUE THREAD

**Issue by staticssleever668** [narzoul/DDrawCompat#82] opened 2020-12-28 17:27 UTC
When a new experimental version is released, the previous one gets deleted. It would be nice if instead every experimental version had it's own tag. This way in case something that worked in previous experimental version breaks in the latest, the old one can be downloaded again. It would also help to search for regressions.

Speaking of releases, isn't it time to increment DDrawCompat's version? Like, it's been over four years since the last real release.

**Comment by narzoul** [comment] 2021-01-04 23:03
I don't want to clutter the releases page with dozens of untested releases. I do still have the last 30 or so experimental releases offline, I could put them somewhere if there's really an interest. I don't use them much for finding the source of regressions because git bisect is more accurate (and rarely needed also).

The version will be incremented when I have enough time to properly test it with a high number of games and deem it to be stable enough. Right now there are still several important issues to be fixed. I don't want to create a half-baked release that's full of bugs and possibly worse than the previous one. The aim is to fix at least the ones that can be done without introducing config options, and the leave the rest for a later release after configs are introduced.

**Comment by J1327** [comment] 2021-04-08 18:13
Experimental works great , as example for : "new barmalei" which use's 8bit / 16bit draw color palette only - this is perfect fix for this game (as specially then running on win 10 ) , thanks

**Comment by narzoul** [comment] 2021-04-08 23:15
Well, I've finally released v0.3.0. Hopefully, new releases will be a bit more frequent now.

**Closed by narzoul** 2021-04-08 23:15 UTC
