### ISSUE TITLE
Dark Earth screen transition effect

### ISSUE THREAD

**Issue by KainXVIII** [narzoul/DDrawCompat#260] opened 2023-11-18 18:21 UTC
Is there any way to emulate it properly, like on this video https://youtu.be/rDOeZmh1ao8?t=257 (with timestamp)
With DDrawCompat its just turn to black and that's it.

**Comment by narzoul** [comment] 2023-11-19 17:05
The problem is that the game keeps the primary surface locked during the entire transition effect, and just keeps updating it via the CPU while it's locked. This may have worked on GPUs available at the time, but even then it was undefined behavior, not really supported by DirectDraw.

I'm not sure what's the best way to support this. It's not the only game doing "bad" things like this. For now, I just put together a quick hack to make it work:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/13403912/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/13403913/diff.txt) compared to v0.5.1)

**Comment by KainXVIII** [comment] 2023-11-19 19:22
> The problem is that the game keeps the primary surface locked during the entire transition effect, and just keeps updating it via the CPU while it's locked. This may have worked on GPUs available at the time, but even then it was undefined behavior, not really supported by DirectDraw.
> 
> I'm not sure what's the best way to support this. It's not the only game doing "bad" things like this. For now, I just put together a quick hack to make it work: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/13403912/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/13403913/diff.txt) compared to v0.5.1)

Amazing work anyway (even if its "just" a hack)!

**Comment by narzoul** [comment] 2024-04-21 21:45
Fixed in v0.5.2.

**Closed by narzoul** 2024-04-21 21:45 UTC
