### ISSUE TITLE
Road Rash (1996 PC Game) crashes after a while being in the menus

### ISSUE THREAD

**Issue by De-M-oN** [narzoul/DDrawCompat#197] opened 2023-02-02 03:23 UTC
I first said that Road Rash runs flawless, but I was wrong because I wasnt long in the menus and directly started the race.
It crashes after a while navigating through the menus, It can be after 10 seconds, sometimes about 30 seconds.
I tried single core. I tried 60fps Limit. I tried borderless, I tried software device at "app".
in-race it works stable. Its just the menus being high danger.

The game works 100% stable if you run it native without your wrapper, but it would be better if it would work either with your program or with dgvoodoo2 to avoid that low resolution. But both have issues with the menus :-(

Also OBS cant capture the game with game capture. With Monitor capture it works, but its a bit slow at transitions (menu to videoclip, videoclip to in-race and so on) so that I would prefer game capture. Not sure if you can do sth about this.

**Comment by narzoul** [comment] 2023-02-02 22:54
Does it crash or does it freeze? I can only repro the freeze. It's a GDI deadlock caused by display scaling I think. I already fixed it in my dev version. I think you can work around it in the meantime by using DisplayMode=app.

OBS likely only works in Display Capture mode. Game capture probably uses DX hooks which could be incompatible with DDrawCompat's hooks. Such cases are not supported, as per the [readme](https://github.com/narzoul/DDrawCompat/blob/master/README.md).

**Comment by De-M-oN** [comment] 2023-02-02 23:45
It freezes, yeah. Music keeps playing, but mouse is frozen and task manager says its not responding and I have to kill the task (by navigating to the taskmanager via the alt+tab thumbs, then use arrow keys and check again in alt+tab thumbs if I highlighted roadrash, and then I can kill it with ALT+E :D

Well on DisplayResolution app I'm on 640x480 again. But 8x MSAA seems still applied though at least if I didnt observe wrong.

Game Capture of course tries to hook into the game renderer. Display capture would be ok if it wouldnt be so slow on the said transitions. Maybe I can improve that with borderless idk.

**Comment by De-M-oN** [comment] 2023-02-03 02:37
I tried now DisplayResolution App, but it freezes the very same. The only difference is that the mouse still can be moved (but menu doesnt react to mouse movements or anything)

**Comment by narzoul** [comment] 2023-02-03 20:31
Strange, maybe you're also using ResolutionScale? Anyway, this temporary fix should work with both display and resolution scaling: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10582565/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10582567/diff.txt) compared to v0.4.0)

**Comment by De-M-oN** [comment] 2023-02-03 21:25
That one works 👍 
When will the next version round about being released? or completely unknown for now?
Because I really would like to have the stretching to fullscreen.
Then I could continue my "lets play" to the game.

**Comment by narzoul** [comment] 2023-02-03 21:35
I don't know yet. Too many issues, too little time.

But if that's all you need, it can be hardcoded very easily.
Here you go: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10582928/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10582929/diff.txt) compared to v0.4.0)

**Comment by De-M-oN** [comment] 2023-02-03 21:37
you're a life saver, thank you so much 😍

**Comment by narzoul** [comment] 2023-11-13 20:18
The deadlock is fixed in v0.5.0. Also you can use the [DisplayAspectRatio](https://github.com/narzoul/DDrawCompat/wiki/Configuration#displayaspectratio) setting to stretch to full screen.

**Closed by narzoul** 2023-11-13 20:18 UTC
