### ISSUE TITLE
Issues with Arcanum: Of Steamworks and Magick Obscura

### ISSUE THREAD

**Issue by Mac-at** [narzoul/DDrawCompat#16] opened 2017-05-07 15:18 UTC
Greetings on behalf of the team Multiverse Team! Our team is revisioning the classic role-playing game Arcanum: Of Steamworks and Magick Obscura.

On late Windows operating systems there were problems with the performance of the game. Wine D3D solved the problem of slowing down, but at the cost of interface artifacts in the World Editor and changing the animation of the characters in the game, and when interacting with some objects that provide for animation. At the same time, this effect passed after some actions in-game.
Despite this for the stability of the game WineD3D was preferred by our team. In total, 3 files were used - ddraw.dll, libwine.dll and wined3d.dll.

The alternative was the DXWnd wrapper, but with it the game worked slower, there were slowing down, longer downloads and other colors in the game. Preferably it was WineD3D.

Recently we tried to use DDrawCompat. It greatly improves the performance of the game and excludes the above-mentioned artifacts in the world editor! **But at the same time there was one minor problem in the world editor - when folding, the map sector window becomes completely black.** And it helps only to restart the world editor (again, until the next window is minimized). In this case, you can switch between the windows of programs without minimizing the editor window, then this problem will not be.

And here is a screenshot for more visibility.

![i1034 cimgpsh_orig](https://cloud.githubusercontent.com/assets/28508787/25782307/bdf20ce0-3350-11e7-87c9-248a0fc3eac5.png)

Texet duplicates when scrolling some selectors, such as selecting a card or naming something or someone (NPC):

![ddrawcompat test 3](https://cloud.githubusercontent.com/assets/28508787/25783748/132cb034-336a-11e7-8934-1791cae3f9e1.png)

It'll be nice if this bugs is fixed.

In any case, we express great gratitude for the work done!
Thank you for the wonderful wrapper!

P.S. Is it possible to support Cyrillic keyboard?

**Comment by narzoul** [comment] 2017-07-14 09:02
I've had some time to look into these issues now and it seems the black screen after restoring minimized window no longer occurs with the latest experimental release. Can you confirm?
I've known about the scrolling glitch for a while now, but haven't got around to fixing it yet, will do.

I don't understand your question about Cyrillic keyboard support, what exactly is not working? If it's not a graphical issue then I likely can't fix it in scope of this project.

**Comment by narzoul** [comment] 2017-07-16 21:05
Scrolling issue should also be fixed now, please check the latest experimental release.

**Comment by Mac-at** [comment] 2017-08-05 20:15
Hello Narzoul,
 
Thank you very much for your answer.
Actually I no longer expected to receive an answer.
 
It works, but scrolling became abruptly, unlike the release version.
 
With the early ddraw.dll in the World Editor selectors, you could press, 
for example, F-button on the keyboard and it will jump to the word which starts 
from F. But with the new ddraw.dll it works only with English keyboard and we 
cannot jump to Russian words. It’ll be nice to fix it.
 
Also when software renderer is disabled (software=0 in config.ini), and some NPC with a lamp passes next to another source of lighting – FPS drop.
If software renderer is enabled (software=1 in config.ini), then there will be no FPS drop, but graphical issues appeared (Fig. 1-2). This problem is solved by loading between locations, loading a saved game, etc. So this bug is not constant with software renderer.
Is it possible to implement something, so that there are no  FPS drop  with a 
software renderer?
 
When are you planning to release the new version?
We’re planning to release Arcanum RePack this month.
 
 
Anyway, thank you very much for your efforts and good luck to you.
 
Best Regards.

**Comment by narzoul** [comment] 2017-08-06 17:08
Abrupt scrolling: I assume you mean the lack of smooth scrolling? That is intentional to fix scrolling issues in full screen mode. In windowed mode it could currently work because GDI emulation is not yet implemented there, but I plan to do it in the future and then I think enabling smooth scrolling could cause similar problems. Nevertheless I can put it back until then if necessary, and then see how it goes once I get to work more on handling windowed apps.

Jump selection with keyboard shortcuts: I can't reproduce the problem. I only have the English version of the world editor so the only place I found where I could experiment is the File / Save As menu where I can input map names with Russian keyboard layout. But selecting them through the keyboard works correctly there.
Are you sure this is related to DDrawCompat and that it works correctly without it? I can't think of any change that should mess with keyboard input like this.

Software renderer: I have no idea what this is. There is no config.ini in my Arcanum installation. Is this from the high resolution patch? There is a "Renderer" setting there but it's still not really well documented.
Nevertheless I can possibly check if the performance issue is DirectDraw related, but I'd need a save game that can reproduce the problem. I'm not familiar with the game and I don't really have time to play it until I randomly run into the mentioned conditions.

I don't have a release schedule, but I think with the amount of issues left and how little time I have to work on them, a release this month is highly unlikely.

**Closed** 2020-04-29 18:37 UTC
