### ISSUE TITLE
Config Overlay not working

### ISSUE THREAD

**Issue by Pinstripe666** [narzoul/DDrawCompat#325] opened 2024-06-04 10:10 UTC
When I enable it with Shift+F11, I get a black window, with the mouse cursor being a black box. I tested this only with Arcanum.

**Comment by narzoul** [comment] 2024-06-04 11:31
Please reproduce the issue with debug logs enabled by setting LogLevel=debug in DDrawCompat.ini. Then attach the DDrawCompat log file.

**Comment by Pinstripe666** [comment] 2024-06-04 11:35
https://easyupload.io/eooegn

Hope that helps.

**Comment by narzoul** [comment] 2024-06-04 12:08
I don't have much time to look into it now, but I have some quick initial observations/questions.

Your user mode display driver is something I've never seen before: atidx9loader32.dll. Can't even find anything about it on google, and it's not part of my own AMD GPU driver package either. What kind of GPU is it?

Your game resolution seems to be 1366x768, which doesn't sound normal for this game. How did you set it? Do you have some mods installed, and which ones?

You've changed some settings like DpiAwareness and FullscreenMode, but I'm not sure why, or whether they could be related to the issue. Have you tried the default settings?

What is your Windows DPI scale factor?

**Comment by Pinstripe666** [comment] 2024-06-04 13:26
Okay, so I've now used the AMD Cleanup Utility to uninstall and reinstall my graphics drivers, and got rid of the mysterious "atidx9loader32.dll" in DXDIAG. The game now hooks with "amdxn32.dll.dll", but alas, still the same half-transparent black window with a green line on top of it.

**Comment by Pinstripe666** [comment] 2024-06-04 14:04
The overlay does indeed display correctly in the World Editor!

Here's what it looks like in-game:
https://postimg.cc/YvzpzcWq

**Comment by Pinstripe666** [comment] 2024-06-04 14:18
Also tested it with Baldur's Gate 2 (original, not EE). Same thing.

It's no biggy though. Probably something on my end.

**Comment by narzoul** [comment] 2024-06-04 19:53
Does this work? [ddraw.zip](https://github.com/user-attachments/files/15569681/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/15569683/diff.txt) compared to v0.5.2)

If not, could you check if any of the previous versions with overlay support (v0.4.0, v0.5.0, v0.5.1) works?

**Comment by Pinstripe666** [comment] 2024-06-05 06:02
Thank you. Your provided dll does work indeed! So does v0.5.1. and v0.5.0! 

It's only the v0.5.2 where the overlay is broken.

**Comment by elisimpson** [comment] 2024-06-23 13:44
Just adding a "me too" ... overlay broken with 0.5.2 but works with 0.5.1. Tested game is Syberia 1 from GOG. Graphics card is Radeon 780.

**Comment by narzoul** [comment] 2024-07-02 23:14
Fixed in v0.5.3.

**Closed by narzoul** 2024-07-02 23:14 UTC
