### ISSUE TITLE
Rainbow Six Black Ops (Rogue Spear) crashes with Gsync enabled

### ISSUE THREAD

**Issue by Mitch037** [narzoul/DDrawCompat#333] opened 2024-06-28 01:51 UTC
I've given a try to [Rainbow Six: Black Ops 2.0](https://www.moddb.com/mods/rainbow-six-black-ops-20) (which contains DDrawCompat by default) and I've noticed the game crashes at startup when G-sync is enabled. Would it be possible to fix it? I have got a native Nvidia G-Sync monitor so I can provide some debugging if it would help. To make it worse I still use Windows 7 x64 😄 As a result I cannot launch the game in **borderless** mode as it simply doesn't work with Win7 so I launch the game in **exclusive** mode.

**Comment by narzoul** [comment] 2024-06-28 10:09
Last year I upgraded to an NVIDIA 3060 Ti, and I could reproduce this issue too with a Freesync monitor ("GSync Compatible") on Windows 11. I checked if it could be worked around somehow back then, but I found no solutions. It crashes always in the Present routine of the driver and I found no way to avoid it other than to disable GSync.

Several months ago, sometime at the end of 2023 I think, the issue was actually fixed by an NVIDIA driver update, and I can no longer reproduce it on my system since then, even with the current latest drivers. But since Windows 7 has reached EOL a long time ago, I assume NVIDIA is no longer shipping such driver updates there, so you're out of luck.

You'll have to either upgrade to a supported OS, or live with disabling GSync in such cases. There's nothing I can do about it.

**Closed by narzoul** 2024-06-28 10:09 UTC
