### ISSUE TITLE
Claw (1997) Sky Background Bug

### ISSUE THREAD

**Issue by OpenRift412** [narzoul/DDrawCompat#201] opened 2023-02-11 18:22 UTC
So there's a weird bug I've noticed when using DDrawCompat with Claw where the sky background only seems to load in chunks, and the areas of the sky background that haven't loaded just show black. This seems to work fine with dgVoodoo's DDraw, though.

Here is a comparison at the beginning of level 3, checkpoint 2. Notice the black bit near the top of the screen with DDrawCompat.

dgVoodoo:
![image](https://user-images.githubusercontent.com/29780788/218274641-359e663c-c692-427e-bb3e-0c2094162b26.png)

DDrawCompat:
![image](https://user-images.githubusercontent.com/29780788/218274760-2c2bc1bf-5da2-43f5-b4f6-e2aae4ee6097.png)

**Comment by narzoul** [comment] 2023-02-12 16:45
I cannot reproduce the issue. I played through the entire level without any glitches. Also tried loading that particular checkpoint several times, but it always looks fine.

Is your game patched to v1.3? Are you using default settings with DDrawCompat v0.4.0? Have you tried older releases?

**Comment by OpenRift412** [comment] 2023-02-12 16:53
> I cannot reproduce the issue. I played through the entire level without any glitches. Also tried loading that particular checkpoint several times, but it always looks fine.
> 
> Is your game patched to v1.3? Are you using default settings with DDrawCompat v0.4.0? Have you tried older releases?

I'm using v1.3, the latest version of DDrawCompat and I just tried with default settings, but nothing fixes it. Older releases of DDrawCompat don't work at all, it just shows a black screen for a few seconds and then crashes.

**Comment by narzoul** [comment] 2023-02-12 16:59
Please set LogLevel=debug in DDrawCompat.ini, load that checkpoint, then when it's fully loaded, exit the game via Alt+F4. Upload the log file (compressed if possible). Thanks!

**Comment by OpenRift412** [comment] 2023-02-12 17:25
Here you go:
[DDrawCompat-CLAW.zip](https://github.com/narzoul/DDrawCompat/files/10716738/DDrawCompat-CLAW.zip)

**Comment by narzoul** [comment] 2023-02-12 18:24
It turns out to be a driver difference affecting only NVIDIA. In order to support palettized textures, DDrawCompat replaces the P8 format with L8. But then the drivers seem to disagree on which component of a 32-bit ARGB color should be used for color fills on an L8 surface. AMD and D3D9On12 use the red channel, but NVIDIA uses the blue channel.

One solution is to set both the red and blue channels, which seems to be working for all drivers, but it still seems rather clunky. Instead, I'll replace the L8 format with R8 for now, which at least seems to work consistently on all drivers. Hopefully, it won't introduce other problems.

Here is a test version:  [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10716855/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10716856/diff.txt) compared to v0.4.0)

**Comment by OpenRift412** [comment] 2023-02-12 19:59
Awesome, that seemed to fix it!

**Comment by narzoul** [comment] 2023-11-13 20:23
Fixed in v0.5.0.

**Closed by narzoul** 2023-11-13 20:23 UTC
