### ISSUE TITLE
Rainbow Six missing grill textures

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#240] opened 2023-08-07 12:36 UTC
This is an old issue with DDrawCompat and I guess it's time to have it fixed.

The game has issues with transparent glass and missing grill on Nvidia hardware; and only missing grill on Intel hardware 

DDrawCompat fixes the transparent glass on Nvidia hardware, but not missing grill.
![R6_1998_fence_HAL](https://github.com/narzoul/DDrawCompat/assets/64649734/68d62fae-f09c-4cf3-8ae3-75db6ace550b)

Please have a look into it.

**Comment by narzoul** [comment] 2023-08-07 14:26
I have a "fix" (config option) already, but it's not yet published. The issue is as described by Dege here:
https://www.vogons.org/viewtopic.php?p=427054#p427054

This issue is basically a duplicate of https://github.com/narzoul/DDrawCompat/issues/159, where you reported the Extreme G-2 intro text rendering glitches on NVIDIA. I wrongly concluded that it had something to do with alpha blending, but it was not correct. Dege's explanation is right, and the same solution works for both cases. Hence I will close this as a duplicate, the issue can be tracked in the other thread.

A fix will be available only in the next release. No test versions this time, since there are too many changes compared to v0.4.0 and it would be non-trivial to backport.

**Closed by narzoul** 2023-08-07 14:26 UTC

**Comment by narzoul** [comment] 2023-08-07 14:32
Btw, TextureFilter=point can be used as a workaround, but of course it degrades the quality of other textures too.
