### ISSUE TITLE
Beach Life, 2002 wont start with DDrawCompat

### ISSUE THREAD

**Issue by MauriceAvecWii** [narzoul/DDrawCompat#66] opened 2020-05-10 00:40 UTC
Just heard about your "tool" and tired it out. Saw it in this [video ](https://www.youtube.com/watch?v=fasotR-uP-U )that it works with the game. I tried it by myself and the game wont start all I get is a black screen,

[Debug Log](https://pastebin.com/qFHTxFbf)

My guess some programm I'm running is causing this

System:
MBD: MSI B450 Tomahawk
CPU: AMD Ryzen 5 2600 @4,0Ghz
RAM: G.Skill Aegis 16GB DDR4 @3000Mhz
GPU: ASUS Radeon RX Vega 64 8GB
MN1: ASUS VG278Q 27" @144hz
MN2: Samsung Syncmaster BX2450L 24" @60hz

**Comment by narzoul** [comment] 2020-05-10 08:45
I can't reproduce the issue and there is nothing obvious wrong in your logs. It looks like you're not using Windows 10 though. Are you on Windows 7?

Please see if any of the following helps:
1. If you have your desktop extended to both monitors, try using only 1 of them at a time. Try each monitor separately.
2. If you have high DPI scaling enabled (greater than 100%), set it back to 100%.
3. Close all other apps that could be interfering, such as video recorders (like Fraps), overlays, RivaTuner, etc.
4. If you have disabled desktop composition, try turning it on.
5. Disable all compatibility settings on the executable file.

If none of the above helps, please attach a crash dump + the debug logs from the same test.

If the application crashes back to the desktop by itself, you can check my instructions here on how to automatically create a crash dump: https://github.com/narzoul/DDrawCompat/issues/50#issuecomment-520162844

If it doesn't crash, just hangs on a black screen, try opening Task Manager, right click on the executable file (might be on the Details tab depending on Windows version) and select "Create dump file" from the menu. Afterwards you can terminate the application from there too by right clicking on the executable again and selecting "End task".

**Comment by narzoul** [comment] 2020-05-29 19:26
@MauriceAvecWii Any feedback on this? I can't reproduce the issue, so I'll definitely need support in resolving it.

**Comment by narzoul** [comment] 2020-08-04 18:51
Unable to reproduce and no response, so closing.

**Closed by narzoul** 2020-08-04 18:51 UTC
