### ISSUE TITLE
[0.5.2+Unreal Engine 1.x] Peculiar behaviour for UseDirectDraw=False

### ISSUE THREAD

**Issue by donizettilorenzo** [narzoul/DDrawCompat#308] opened 2024-05-06 13:08 UTC
Test done in Windowed Mode (1920x1440 over 2560x1440 Win11 desktop)
Intel ARC A380 with lastest drivers

In the previous version using in the game engine config file UseDirectDraw=True or UseDirectDraw=False do not differ in behaviour
With 0.5.2 UseDirectDraw=False make the screen "freeze" in 2D menus (not the game, only the screen freezes holding the last frame) **until you ALT+TAB**.

UseDirectDraw=True solves the problem

Is this expected?
You can just check with Unreal Tournament 99 and the old DDRAW renderer

**Comment by donizettilorenzo** [comment] 2024-05-06 14:55
Oh well, you did encounter it too!

_except the screen freezes on the loading screen initially, but it's fixable by moving the window or clicking outside of it. That's an odd issue, I'll look at it later._

**Comment by narzoul** [comment] 2024-05-06 18:07
I can't reproduce the issue with either Unreal Gold or Unreal Tournament GOTY (both GOG versions). Have you checked if the patch I linked fixes it for you?

**Comment by donizettilorenzo** [comment] 2024-05-06 19:49
It seems so!

**Comment by narzoul** [comment] 2024-07-02 23:07
Fixed in v0.5.3.

**Closed by narzoul** 2024-07-02 23:07 UTC
