### ISSUE TITLE
Beast Wars Transformers

### ISSUE THREAD

**Issue by ghotik** [narzoul/DDrawCompat#358] opened 2024-09-08 13:57 UTC
Here is another curious case: Beast Wars Transformers (that requires a DxWnd tweak to run without crashing) shows tiny and unreadable texts on screen. Making some experiments, I found that the text is a pre-defined part of a texture (see images) and that dgVooDoo2 improves the situation making the text readable. Neither the system ddraw.dll, nor the DirectDrawCompat wrapper seem able to get the same result. My guess is that there could be a problem of unsupported transparencies or texture formats, but I think you would know better.
As usual, some discussion was here: https://sourceforge.net/p/dxwnd/discussion/general/thread/ec4acf851b/#ee1c
If you want to run the game on a modern computer you can find there some working DxWnd profiles.
Do you have any suggestion about this case?

The screenshot unreadable_text.png was using the system ddraw.dll, while readable_text.png was using dgVoodoo2
P.s. I see now an even more curious fact: dgVoodoo2 fixes the text "Continue" and "Quit" but makes invisible the title "Quit Game?".

![texture 256 256 R5G6B5 7922BB6A](https://github.com/user-attachments/assets/0eeca068-bb2d-44ab-b126-19e5f999affd)
![unreadable_text](https://github.com/user-attachments/assets/6f54bfda-90ab-4369-8a74-21cd2b3d6f96)
![readable_text](https://github.com/user-attachments/assets/59ba7588-beed-4616-934f-abf9022f288c)

**Comment by narzoul** [comment] 2024-09-08 16:36
I couldn't get the game to start even with DxWnd, so I had to do some debugging on my own.

I installed it using otvdm to get around the 16 bit installer. Applied the official patch (from patches-scrolls).

After that, the game just exits immediately on launch without any error messages. Debugging that for a while, I tracked it down to a version check based on GetVersionExA. The game seems to refuse to run on NT based OSes. Using WinVersionLie=98 in DDrawCompat bypassed that.

Then, there were obvious problems with the movies, so I created an ISO without the FMV folder and used that to launch the game. It got a little further after that.

Afterwards, it crashed with an access violation, trying to read from a null pointer. Bypassing that with the IgnoreException shim was pointless, as it just lead to a black screen, and in the logs I saw a bunch of invalid Direct3D calls with the "this" pointer set to null, right after the point where the exception was bypassed.

I saw that the game is using the legacy Ramp device, so I tried with the native one, using the SoftwareDevice=app setting of DDrawCompat. That gets to a black screen again, but pressing enter gets into the main menu, with bad colors as expected from the broken Ramp device on modern systems.

Then I put an older version of d3dim.dll in the game folder, 10.0.17134.1, which is the last working version with proper Ramp device support, based on my old research: https://github.com/narzoul/DDrawCompat/issues/22#issuecomment-616197074

That seems to have fixes all graphics issues, except for a minor glitch near the text that scrolls up when starting a mission. I suppose this dark red line on the left side shouldn't be there, but I don't really have any reference results to compare it to:
![text](https://github.com/user-attachments/assets/9c18a7ca-62b9-4195-9dee-1581b50fe602)

But other than that, everything seems to render fine. I haven't noticed any other text issues. The hardware mouse cursor is not hidden, which could probably be easily patched, but I didn't bother to investigate that one.

**Comment by BEENNath58** [comment] 2024-09-19 18:03
Run the game in 3d mode (use videosetup)
The game is supposed to look like this:
![menu](https://github.com/user-attachments/assets/6cb630ef-a1ae-454e-82d5-1622997df919)

but instead looks like:
![menu1](https://github.com/user-attachments/assets/6458f221-367d-4e83-980a-bc3194e731aa)

**Comment by BEENNath58** [comment] 2024-09-19 18:22
You are looking at the wrong spot: you need to change the renderer to 3D card in VideoSetup. It should be in the All Programs menu, or look for C:/Windows/BWSetup./exe

**Comment by narzoul** [comment] 2024-09-19 19:01
That looks fine too except for text, which is easily fixed by AlternatePixelCenter=on.

**Comment by BEENNath58** [comment] 2024-09-20 06:37
I turned that on, but I am not sure it is correct. It works at least, I can confirm, with the Continue and Quit options on pressing Escape
![Screenshot 2024-09-20 120350](https://github.com/user-attachments/assets/fb01f738-5aae-4402-bfe1-ab4d46ea4da1)

On period correct hardware
![actual](https://github.com/user-attachments/assets/ce08825a-1ea2-43d0-bba2-94f49811f896)

**Comment by narzoul** [comment] 2024-09-20 07:25
Is that on NVIDIA by chance? If bilinear filtering is enabled in the game, it is also applied to that text, which doesn't play well with NVIDIA's color key method. Try ColorKeyMethod=alphatest(1) instead.

But I think it's better to keep text point filtered. For that, use SpriteDetection=zconst and SpriteFilter=point.

**Comment by ghotik** [comment] 2024-09-20 08:58
Good point, I think I'll try to copy some of these features in DxWnd, always if you don't mind.
Do you have a list of some other oldies that can have the need for AlternatePixelCenter for testing? I never met one, but perhaps I didn't watch attentively.
Thanks so much!

**Comment by BEENNath58** [comment] 2024-09-20 09:20
> Do you have a list of some other oldies that can have the need for AlternatePixelCenter for testing? I never met one, but perhaps I didn't watch attentively.

NFS Porsche Unleashed comes up regularly. I think hooking this one will need driver intervention. 

And yes it's quite a common feature required in old games, I just can't remember more

**Comment by ghotik** [comment] 2024-09-20 10:41
Wow, my tentative fix works, all the tiny font textures are now perfectly visible:

![dxwndfix](https://github.com/user-attachments/assets/0069e6f8-a448-47d8-a9f6-22f9a3410beb)

I may ask you a little additional help. I added the patch at the application level in the Direct3D1-7 DrawPrimitive wrapper, so this will at the moment exclude D3D8/9 or higher. But I suppose you didn't follow this way, surely you fixed the vertices at the d3dumddi level in some callback. So may I ask ...
1) which is the callback? I suppose one or more of the pfnDrawPrimitive* callbacks, is that correct?
2) what type of vertices should be patched? In Beast War Transformers it is necessary to patch the sx and sy fields of the D3DVT_TLVERTEX type vertices, but supposedly also the D3DVT_VERTEX and D3DVT_LVERTEX should be patched or not?

Thanks in advance

**Comment by BEENNath58** [comment] 2024-09-20 11:02
> ColorKeyMethod=alphatest(1)
> If bilinear filtering is enabled in the game, it is also applied to that text, which doesn't play well with NVIDIA's color key method.

Disabling bilinear filtering works, as well as changing the color key method. Thanks.

> But I think it's better to keep text point filtered. For that, use SpriteDetection=zconst and SpriteFilter=point.

The two setting didn't change anything

**Comment by ghotik** [comment] 2024-09-20 17:50
Hi again.
I compared the results of your AlternatePixelCenter=on with my tentative fix adding the -0.5f value to the sx and sy fields ot the TNLVERTEX structures processed by DrawPrimitive. The result is that your implementation is more correct because fixes the pixel center only to text sprites, while my implementation adds the offset also to textures in the scene that wouldn't need to be fixed.
The attached picture shows some of the effect of my implementation with defects that are not present neither in the original game, nor in the DDrawCompat fix.
![dxwnd_defects](https://github.com/user-attachments/assets/edb9db73-4d67-4f27-b80f-cc7b0a1e3674)

I tried to select the vertices that needed a fix by testing the sz coordinate, but that didn't seem a good criteria.
So, I'd like to add a third question to the previous two:

3) how do you determine whether a vertex should be fixed or not?

**Comment by narzoul** [comment] 2024-09-20 19:20
> Do you have a list of some other oldies that can have the need for AlternatePixelCenter for testing?

Not really, but in my experience most games need it. The article that explained how to directly map texels to pixels first appeared in the DX7 SDK if I remember correctly, so probably just about everything developed before that got it wrong. But it's possible that it's not just the games' fault, and drivers/hardware back then may have had the same wrong concept about where pixel centers should be, and perhaps the reason everything looked right anyway was because two wrongs in this case do make a right.

Anyway, the problem is not always noticeable. It tends to get worse when things like resolution scaling, antialiasing or fancy texture filtering are forced. In theory, you could figure out which games need it by inspecting the X/Y coordinates of transformed vertices. If the min/max values per frame are close to an integer, it's likely needed. If it's closer to halfway between two integers, then it's probably not needed. I wanted to add a stat about it to DDrawCompat, but didn't have time for it yet.

> I may ask you a little additional help. I added the patch at the application level in the Direct3D1-7 DrawPrimitive wrapper, so this will at the moment exclude D3D8/9 or higher. But I suppose you didn't follow this way, surely you fixed the vertices at the d3dumddi level in some callback. So may I ask ...
>
> 1. which is the callback? I suppose one or more of the pfnDrawPrimitive* callbacks, is that correct?
> 2. what type of vertices should be patched? In Beast War Transformers it is necessary to patch the sx and sy fields of the D3DVT_TLVERTEX type vertices, but supposedly also the D3DVT_VERTEX and D3DVT_LVERTEX should be patched or not?

> 3. how do you determine whether a vertex should be fixed or not?

I think this was all already discussed at length here: https://github.com/narzoul/DDrawCompat/issues/324
The same situation applies here. Only those vertices need to be offset that have the D3DFVF_XYZRHW flag in the FVF format description. Also make sure you operate on a copy and not the original vertices, in case the game feeds the same memory multiple times to draw calls, in which case you'd end up accumulating the offsets. Or you might also be doing this accidentally if indexed vertices are used and the same index is used multiple times.

> The two setting didn't change anything

It doesn't change anything if you already disabled bilinear filtering. Otherwise it should pretty clearly affect the text you showed earlier with the title "On period correct hardware". The difference is the same as with the bilinear on/off setting of the game. You can experiment with it from the overlay to see it more clearly.

> I take advantage of this post to tell you that DDrawCompat behave brilliantly except for one case. In one of the mission presentation screens your AlternatePixelCenter skips one text panel that becomes quite hardly readable (see screenshot), probably because of the selection criteria.

This was already addressed a few comments earlier:
> Is that on NVIDIA by chance? If bilinear filtering is enabled in the game, it is also applied to that text, which doesn't play well with NVIDIA's color key method. Try ColorKeyMethod=alphatest(1) instead.

**Comment by BEENNath58** [comment] 2024-09-20 22:25
> It doesn't change anything if you already disabled bilinear filtering. Otherwise it should pretty clearly affect the text you showed earlier with the title "On period correct hardware". The difference is the same as with the bilinear on/off setting of the game. You can experiment with it from the overlay to see it more clearly.

Okay I guess what I saw is "less-pixelated" then expected usually with point sampling so I didn't notice. Anyways thanks.

**Comment by ghotik** [comment] 2024-09-21 09:37
Thank you again, your hints were a success.
I took advantage of the previous implementation of the vertices zooming ( https://github.com/narzoul/DDrawCompat/issues/324 ) to add in the same dxwnd procedures the x,y vertices correction. It works, but I still got a question:
My code now works perfectly with this game despite the fact that I didn't implement your suggestion "Only those vertices need to be offset that have the D3DFVF_XYZRHW flag in the FVF format description". This is probably a lucky case where this check is not necessary, but I can't understand where this flag is located. Where is it? I apologize, I imagine that the question is trivial, but ...
A good candidate seemed D3DDDI_RESOURCEFLAGS, but there is no flag with a matching name. Perhaps it is the Fvf field of the D3DDDIARG_CREATERESOURCE structure that feeds pfnCreateResource? In this case should I create an association to tell which resources are suitable candidates to be fixed?

**Comment by narzoul** [comment] 2024-09-21 10:19
The D3DFVF_XYZRHW flag is used in the runtime. It is passed directly to the Draw functions (dwVertexTypeDesc parameter), except in the Draw*VB cases. For the VB variants, it is part of the vertex buffer description passed to CreateVertexBuffer (dwFVF member in D3DVERTEXBUFFERDESC).

For the driver, it was already discussed in the other issue: https://github.com/narzoul/DDrawCompat/issues/324#issuecomment-2156433939 (specifically under the Flexible Vertex Format header). I think it is already pretty detailed, so it would be more useful to know which part of that is unclear. But to recap, at draw time, check the current vertex declaration selected by the last call to pfnSetVertexShaderDecl. If that declaration was created with any of the vertex elements' Usage field set to D3DDECLUSAGE_POSITIONT, then you can edit the vertices, otherwise you shouldn't.

**Comment by narzoul** [comment] 2024-09-29 21:08
I put together a small test program, compatible with Win9x, to determine where the "pixel center" is located on various GPUs. I tested it with Win98 SE (PCem) and native Win11. See some results in the Samples directory.
Download (with source code) here: [TestPixelCenter.zip](https://github.com/user-attachments/files/17181270/TestPixelCenter.zip)

It roughly does the following tests:
- The first test (Pixel center) determines approximately which screen-space coordinates correspond to the top-left pixel. According to the [Rasterization Rules](https://learn.microsoft.com/en-us/windows/win32/direct3d9/rasterization-rules) (should apply to DX9 and older), pixel centers are at integer coordinates. If a triangle covers the pixel center, then that pixel should be rasterized, otherwise it shouldn't.
This test tries to determine the coordinates of the subpixel-sized rectangle of width/height=1/2^20 pixels, that covers the pixel center of the (0, 0) pixel, (Note: the actual pixel tested is at (4, 4), adjustable by the OFFSET_X and OFFSET_Y constants in the source code. I chose not to use (0,0) by default to avoid some clipping issues. However, the results are still given relative to the (0, 0) coordinates.)
If the result is `(x, y) / d`, then a rectangle with coordinates `(x/d, y/d)` - `((x+1)/d, (y+1)/d)` should cover the top-left pixel's center. Ideally, this should be exactly at (0, 0), but apparently this is rarely the case in practice, and even modern GPUs have a small offset of ~1/512 pixels. Surprisingly, the offset is the same for AMD/Intel/NVIDIA, and I verified that it is not added by the runtime. I can't find any documentation about why that particular offset is used, Maybe it's some inside info from MS.
- The diffuse test renders a 2x2 rectangle with gouraud shading without textures. The red intensity increases from 0 to 31 from left to right, and similarly the blue intensity increases from top to bottom. The top-left coordinates of the rectangle are at (4, 4). Returns the red and blue color output at the (4, 4) pixel.
- The texture test is similar to the diffuse test, except it uses a constant white diffuse color and a 32x32 texture with similar color progression as above. Texture addressing mode is clamped and texture filtering is set to nearest.
- Each test has a "half-pixel offset" variant, which differs only by the rectangle vertices being shifted by (-0.5, -0.5).

All tests are done in 640x480x16 display mode for best compatibility with all GPUs. Some GPUs seem to refuse to render to any render target other than a fullscreen backbuffer (which means they also can't render in windowed mode). I think this restriction mainly applies to the add-on Voodoo cards.

The results indeed confirm that the Voodoo 1 has approximately a half-pixel offset by default, and correspondingly, it is also the only one that renders text flawlessly in Beast Wars. The others mostly had similar results as DDrawCompat with AlternatePixelCenter=off and ColorKeyMethod=alphatest(1).

So I suppose that most games that were developed/tested mainly on a Voodoo 1 could have similar half-pixel/texel offset problems.

Some other notes on the sample results:
- The Obsidian SB50 should have good looking text based on its pixel center, but it doesn't. The texture test results also look wrong. I may have wrong drivers for it. It also works with the Voodoo 1 drivers, but that gives the same results as the Voodoo 1, so it's not really interesting.
- Text with the S3 ViRGE DX looks surpringly sharp despite its accurate pixel center, but it turns out this might be because bilinear filtering is not working on it. Again, I may have bad drivers for it.
- The Intel UHD 770 pixel center is slightly off from the usual (2048, 2048) coordinates, but this slight error seems to depend on the OFFSET_X/Y values and the size of the viewport. At a viewport size of 16x16 or smaller, it seems to give an exact (2048, 2048) result as well.

**Closed** 2024-11-03 12:54 UTC
