### ISSUE TITLE
Not working at all under Windows 7

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#318] opened 2024-05-23 16:17 UTC
A colleague of mine has been trying to get DDrawCompat working on his system for a while, but it never seems to work for him.

I asked him for a debug log and just by glancing at it I'm not entirely sure what's going on, but my bet is that he borked some important system files along the way and DDC is struggling to hook somehow.

Could you take a look at it? Thank you very much

OS: Windows 7
GPU: GTX 960
CPU: 3rd gen I5

[ddraw log](https://cdn.discordapp.com/attachments/737222846270668841/1243228027014484058/DDrawCompat-nfs4.log?ex=6650b5d3&is=664f6453&hm=458ddc1b0db7612cbbbd56c99ea9b81b77faa0062e5c158f2ef636f001f69ae3&)

**Comment by narzoul** [comment] 2024-05-23 18:43
I have no idea, but it's definitely not a generic Windows 7 issue, because the hooking mechanism works even in a Windows 7 VM (I just double checked).

Is there a dbghelp.dll or dbgeng.dll in his game directory? If yes, try removing those. If not, please check the version numbers of those files in C:\Windows\SysWOW64. Maybe I can reproduce it with whatever version he has there.

**Comment by PlayNeth** [comment] 2024-05-24 03:28
Nothing special going on in the game's folder itself, so here's the details of those specific files:

[dbgeng](https://media.discordapp.net/attachments/737222846270668841/1243401865341960204/image.png?ex=665157b9&is=66500639&hm=988de011321bd5ed40f4170110a3eaaa92aafd87931d60e1c6b762b6bb7d9ef9&)
[dbghelp](https://media.discordapp.net/attachments/737222846270668841/1243401983701028944/image.png?ex=665157d6&is=66500656&hm=0e3441af876ff7de92f26daa884dfa1693648056c5f39aada192b5d8fbd7d0aa&)

**Comment by narzoul** [comment] 2024-05-24 21:48
That's the exact same version I have in my VM, so unfortunately it doesn't help.

Let's just try to skip that problematic call. In theory, the result should be a constant anyway.
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/15440282/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/15440285/diff.txt) compared to v0.5.2)

**Comment by PlayNeth** [comment] 2024-05-25 00:39
There you go:

[ddraw log](https://cdn.discordapp.com/attachments/737222846270668841/1243719291853869179/DDrawCompat-nfs4.log?ex=66527f5a&is=66512dda&hm=efff9b224234c148f3a15488e7b22c6efea41076b8a2fef928ff3ae6206e1d64&)

**Comment by narzoul** [comment] 2024-05-25 09:43
Attempt nr. 2: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/15442551/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/15442552/diff.txt) compared to v0.5.2)

**Comment by PlayNeth** [comment] 2024-05-25 15:00
Still crashing sadly 

[ddraw log](https://cdn.discordapp.com/attachments/737222846270668841/1243941079569399981/DDrawCompat-nfs4.log?ex=66534de8&is=6651fc68&hm=30afbfb820fae87ba9d1e2878f17225898e8e1032e278a06d7f13d7fa9c2c83e&)

**Comment by narzoul** [comment] 2024-05-25 15:39
Thanks, at least the extra logs provide a bit more insight. There are a number of suspicious modules loaded:

`C:\Program Files\Prio\prio32.dll`
I assume this comes from here: https://www.prnwatch.com/prio/
I tried to install it on my VM, and sure enough, it gets injected into the process, but it doesn't seem to cause the hooking to fail.

`C:\Windows\system32\d3d9.dll`
`C:\Windows\system32\d3d8thk.dll`
`C:\Windows\system32\dbghelp.dll`
These are not loaded on my VM, at least not before the hooks are installed. Something must be causing them to be loaded. I tried changing ThrashDriver to dx9 in nfs4.ini, but that didn't matter either. Nevertheless, it would be good to share the nfs4.ini file to sync our settings.

`C:\Users\PDA\Downloads\Need For Speed - High Stakes\DINPUT.dll`
What about this one? It must be some other hook, that could very well be interfering. Where does it come from?

Is this issue present only with NFS games, or with every ddraw game in general?

**Comment by narzoul** [comment] 2024-05-25 15:58
Good news: I managed to reproduce the issue after installing SilentPatch mentioned here: https://www.pcgamingwiki.com/wiki/Need_for_Speed:_High_Stakes#SilentPatch

Looks like this is what provides the dinput.dll file mentioned above.

The issue happens on Windows 7, but not on Windows 11. Anyway, this should at least make debugging it significantly easier.

**Comment by PlayNeth** [comment] 2024-05-25 16:12
Nice!

Yeah that's it, the dinput is ASILoader for his patch.

We use a custom plug&play package of the game optimized for multiplayer in the RetroRacingPoint discord, I have it set to dx7+DDC by default and it runs flawlessly for the vast majority, except for him and some other Windows 7 user  that just crash on boot.

**Comment by narzoul** [comment] 2024-05-25 21:06
So, the problem is this dinput.dll statically links to dbghelp.dll, but dbghelp.dll's DllMain doesn't get called before ddraw.dll's DllMain. It's supposed to create a heap with HeapCreate, which is later used by HeapAlloc in SymInitializeW, which itself is invoked by dbgeng.dll from IDebugControl::WaitForEvent. But because DllMain and thus HeapCreate is not yet called, HeapAlloc ends up getting called with a null pointer as its first argument, which causes an access violation error that breaks the debugger engine.

I don't see a good solution other than linking statically to dbgeng (which itself statically links to dbghelp), which should ensure that dbghelp is initialized before ddraw. But this solution has unfortunate downsides too. For example, some games, such as the GOG version of Settlers 4 has an outdated version of dbghelp next to the main executable, which now prevents the game from launching when DDrawCompat is used. I'm not sure how to work around that anymore.

Anyway, here's the statically linked version, which seems to work on Windows 7 even with the SilentPatch installed:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/15445021/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/15445022/diff.txt) compared to v0.5.2)

**Comment by PlayNeth** [comment] 2024-05-26 02:25
That did the trick! Worked first try for him.

Thank you for looking into it!

**Comment by narzoul** [comment] 2024-07-02 23:10
Fixed in v0.5.3 by removing the dbgeng.dll dependency. It's different than the fix that was posted here, but it should still work.

**Closed by narzoul** 2024-07-02 23:10 UTC
