### ISSUE TITLE
Thief 2 The Metal Age and rendering problems

### ISSUE THREAD

**Issue by fl82** [narzoul/DDrawCompat#81] opened 2020-12-20 14:40 UTC
Hello,
I was trying ddraw with the Thief 2 game in Win 8.1 with also the modern patch that's needed to make it work into new o.s. using the older legacy Directx6 renderer (commenting the ";use_d3d_display" line in the cam_ext file of the patch while many other gpu would be able to use the newer DX9 renderer that unfortunately on this gpu bring many other gfx problems and in that case ddraw.dll seems to not be even called not leaving any log); before this ddraw dll, cause my gpu/drivers it wasn't able to run in real fullscreen mode (probably cause some incompatibilties with 16bit unsupported resolutions and only worked with full-windowed borderless mode with low fps). 
Trying this dll now it seems to start real fullscreen with 32bit colors still with legacy Directx6 engine but better frame rates but I can see strange polygons gfx errors appearing and disappearing depending on the movements and point of view. The config is an Atom dual core with a GMA3600 gpu / SGX545 core. 
An example of the problem that didn't appear before and now appear also in both fullscreen and windowed mode; this appears on the floor textures or walls ones becoming dark and then textures appear again seems depending on the point of view and the lights:

![dx6_rendering](https://user-images.githubusercontent.com/76397937/102716010-4fdaae00-42d9-11eb-92ca-a032e51e21ef.jpg)

This is the log:

_0f84 18:34:19.335 Loading DDrawCompat dynamically from C:\Games\Thief2\ddraw.dll
0f84 18:34:19.342 DDrawCompat loaded successfully
0f84 18:34:19.343 Installing display mode hooks
0f84 18:34:19.345 Installing registry hooks
0f84 18:34:19.345 Installing Direct3D driver hooks
0f84 18:34:19.346 Installing Win32 hooks
0f84 18:34:19.370 Hooking user mode display driver: igdumd32.dll
0f84 18:34:19.420 Dynamic vertex buffers are not available
0f84 18:34:19.420 Dynamic index buffers are not available
0f84 18:34:19.437 Checking source color key support: passed
0f84 18:34:19.459 Installing DirectDraw hooks
0f84 18:34:19.467 Installing Direct3D hooks
0f84 18:34:19.490 Installing GDI hooks
0f84 18:34:19.531 Warning: Failed to hook the following user32 window procedures: [buttonWndProcA,buttonWndProcW,comboBoxWndProcA,comboBoxWndProcW,editWndProcA,editWndProcW,listBoxWndProcA,listBoxWndProcW,mdiClientWndProcA,mdiClientWndProcW,staticWndProcA,staticWndProcW,comboListBoxWndProcA,comboListBoxWndProcW,scrollBarWndProcW,menuWndProcW]
0f84 18:34:19.546 Finished installing hooks
0f84 18:34:19.617 Incorrect z-buffer bit depth capabilities detected for "Intel(R) Graphics Media Accelerator 3600 Series" / Direct3D HAL; changed from "16, 24" to "16"
0f84 18:35:33.408 Detaching DDrawCompat due to process termination
0f84 18:35:33.409 DDrawCompat detached successfully_

The gpu is quite complicated and might be difficult to make it perfectly working but any advice would help. :)
Thanks

**Comment by narzoul** [comment] 2021-01-04 22:42
Could you attach a save game also that reproduces the problem as soon as it is loaded? I tried running around for a while at the start of the game but didn't find any problems.

**Comment by fl82** [comment] 2021-01-06 11:59
For example I attach this first level savegame moment where the floor should be lighted textures and not black triangles and areas (it's needed T2Fix community made patch for the savegame to run I suppose):

[img]https://i.ibb.co/289rMFd/savegame0.jpg[/img]

[game0000.sav.zip](https://github.com/narzoul/DDrawCompat/files/5775604/game0000.sav.zip)

**Comment by narzoul** [comment] 2021-01-08 00:27
Please send me the debug logs also. Just load the save game you sent and exit without moving/looking around.

**Comment by fl82** [comment] 2021-01-08 13:54
Here's the debug log compressed, just launching, loading, rendering few seconds and exiting the game.

[Uploading DDrawCompat-Thief2-Debug.zip…]()

**Comment by narzoul** [comment] 2021-01-08 21:49
The first frame of that save game is rendering completely differently on your system and mine based on the logs. I think we're using different patches or settings, so it's impossible to compare the logs.

What is your game version before installing T2Fix?
Which version of T2Fix did you install exactly, and which components did you select during installation?
Any other patches or mods?

Also, attach your cam_ext.cfg and tell me your video settings in-game, please.

**Comment by fl82** [comment] 2021-01-09 09:55
I suppose probably because the Thief 2 I tried installing the latest v118 official patch _before_ installing the latest v.127d T2Fix. This because if I remember correctly the latest official patch added some things into the game (like those 3D objects in front of the fire in the main hall of the mansion) and other objects that without the patch didn't appear (just an idea).
I'm trying reinstalling the game from zero without the patch v118 and only the T2Fix with minimal setting (just the engine and no graphic/sound modification. The original genuine game cd that I own had the 1.07 game version in the double cd version (brown and black cd's).
Meanwhile I attach the old cam_ext file setting I was using.

[cam_ext.zip](https://github.com/narzoul/DDrawCompat/files/5790445/cam_ext.zip)

**Comment by fl82** [comment] 2021-01-09 10:27
As said I tried also reinstalling the game v.107 from CDs with only T2Fix v.127d with Basic config installation, than modifying the cam_ext commenting the d3d_display line and set 2x anisotropic instead of the heavy 16x one, than added your ddraw.dll in Debug version and then added the savegame. Same result. I attach the logs and results without using any other patches or modifications.

[Log new](https://github.com/narzoul/DDrawCompat/files/5790480/DDrawCompat-Thief2-Debug.zip)
[cam_ext new](https://github.com/narzoul/DDrawCompat/files/5790482/cam_ext.zip)
[game0000.sav.zip](https://github.com/narzoul/DDrawCompat/files/5790484/game0000.sav.zip)

**Comment by narzoul** [comment] 2021-01-09 17:29
Thanks! After some experimenting, I think the issue is related to Z-buffering. The game selects the D24X8 depth buffer format for you. If I force mine to use the same, I get similar display glitches as you on my AMD GPU, but in different places. On Intel HD 4600, there are only smaller glitches, like random lines of various thickness missing from polygons.

There is a "wr_render_zcomp" option in cam_ext.cfg. Commenting it seems to help on my end, does it fix the issue for you?

I'll do some further checks to see if this depth buffer format is broken because of DDrawCompat, or it's just driver issues.

**Comment by fl82** [comment] 2021-01-09 17:46
I tried commenting the wr_render_zcomp line but same problem. I attach the related debug log.
The strange thing is that beside the slow almost unplayable fps with windowed mode without ddraw.dll, the texturing was correct or at least I didn't see visible major problems on all the level I finished the games time ago. So maybe there's something that can solve it.

[DDrawCompat-Thief2-**no_wr_zbuffer** log](https://github.com/narzoul/DDrawCompat/files/5791516/DDrawCompat-Thief2-no_wr_zbuffer.zip)

**Comment by narzoul** [comment] 2021-01-09 18:31
Ok, it looks like commenting that line doesn't completely disable z-buffering either. Let's try a different approach then.
This modified experimental release disables all depth buffer formats, except D16: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5791587/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5791589/diff.txt) compared to 4370990)

I'll need the debug logs only if this doesn't fix the issue either. The wr_render_zcomp option can be enabled for this.

**Comment by fl82** [comment] 2021-01-09 19:07
Thanks but still it shows the same problem. Here's the log.

[Uploading DDrawCompat with no zbuffer log]()

**Comment by fl82** [comment] 2021-01-09 19:19
If this can help, I tried loading the latest (the previous with zbuffer enabled) ddraw into the **Thief 1 Demo** game with similar config, TFix+ddraw-debug where it works perfectly without gfx errors, maybe it says what miss from the different texturing problems.
[Thief-1-Demo Debug Log](https://github.com/narzoul/DDrawCompat/files/5791663/DDrawCompat-Thief1Demo_Debug.zip)

**Comment by narzoul** [comment] 2021-01-09 20:11
The reason I suspected the z-buffer is because on the last screenshot above, the "hole" on the wall in the back is not aligned with the wireframe of the scene, so it looks as if only parts of polygons are missing/corrupt. Here's what the wireframe should look like after loading your last save game, without moving the camera:
![wireframe](https://user-images.githubusercontent.com/16432233/104107707-afb3eb80-52be-11eb-9325-e12dd77d1081.png)

Here's the patch I used for rendering it: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5791762/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5791763/diff.txt) on top of 4370990)

What does it look like on your end? Are the wireframe edges aligned with the glitches?

**Comment by narzoul** [comment] 2021-01-09 20:16
By the way, does DDrawCompat v.0.2.1 not work at all? Does it have the same glitches?

**Comment by fl82** [comment] 2021-01-09 21:05
It's strange with this no-wireframe version it seems that front polygon is  missing in my rendering see the attached screenshot.. also with latest v1.07 new game installation the black shadow is even vertical on both walls.
![Thief2 wireframe](https://user-images.githubusercontent.com/76397937/104108636-9f077380-52c6-11eb-830c-76c68bb3ad52.JPG)

[Log wireframe](https://github.com/narzoul/DDrawCompat/files/5791819/DDrawCompat-Thief2_wireframe.zip)

**Comment by fl82** [comment] 2021-01-09 22:49
UPDATE3: I tried reinstalling the game and as imagined CDs v.107 game + T2Fix 1.27d Basic + ddraw.dll 0.2.1 + **before starting the game** just commented the d3d_display line with notepad and then run the game solved again these "new" problems.. 

![Torch_off_lightmap](https://user-images.githubusercontent.com/76397937/104110061-3e7f3300-52d4-11eb-82b8-8d18768fc088.jpg)

![Main_salon_sofas_vases](https://user-images.githubusercontent.com/76397937/104110062-44751400-52d4-11eb-876b-962ff2ad6e9d.jpg)

I tried exiting the game and reloading a random savegame of the new installation and these until now things are still ok. So I suspect that cam_ext.cfg file with my config or who knows why, maybe should be modified with some specific editor? Or maybe once started the first run of the game I can't modify it cause my system even if I really can't understand how that's possible.
Interesting discovery anyway and I'll do some test again with the newer ddraw.dll at this point. The frame rate is higher than the windowed mode but still suffering in the wide geometric areas. The DX9 renderer would solve that but as said, I suspect my gpu drivers doesn't like both the way D3D9 draw the 2D menu and the rendering itself go fast for a while than stop.. then again it unlock itself and then stop for few seconds and so on... a pain really to debug I suppose.

**Comment by narzoul** [comment] 2021-01-10 13:45
It looks like I was on the wrong track with the z-buffer. As it turns out, my GPUs don't actually support the D24X8 format, but the drivers don't fail the resource creation with it either. So it's not that surprising that the end result was broken.

It's probably one of the 3D optimizations I added to the WDDM driver hooks that broke it after v.0.2.1 for you.
If you're still willing to help with debugging this, please try this version next: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5792664/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5792665/diff.txt) on top of 4370990)
This will disable the suppression of redundant rendering state changes.

**Comment by fl82** [comment] 2021-01-10 14:10
I tried this version on the clean installation I tried above the v0.2.1 not modifying again the cam_ext, and as imagined this works, no gfx errors, no lightmap area problems and sofas and vases remains in the fireplace of the mansion salon. :) But I suspect the strange problem about what happens if I modifying after the first run the cam_ext, might be involved somehow. I'm trying to understand this. Anyway it works on a clean installation! :)

**Comment by narzoul** [comment] 2021-01-10 14:12
So does the latest "official" experimental release also work on a clean install?

**Comment by fl82** [comment] 2021-01-10 14:15
The latest ddraw attached above, yes I've just launched with it and it works. Arrived until the mansion salon and didn't see any gfx errors.

**Comment by narzoul** [comment] 2021-01-10 14:17
No, not the ones attached in these comments. I mean the one here: https://github.com/narzoul/DDrawCompat/releases/experimental

**Comment by fl82** [comment] 2021-01-10 14:18
Ah sorry, I'll try later and update here.

**Comment by fl82** [comment] 2021-01-10 15:38
Here I am. I tried using the experimental version and it still does not work as before even in the clean installation directory. 

![FIrst_room](https://user-images.githubusercontent.com/76397937/104127282-91eb9280-5361-11eb-9075-dd481636a300.jpg)

![External](https://user-images.githubusercontent.com/76397937/104127290-9e6feb00-5361-11eb-8041-8c4b9cb06561.jpg)

I will try using again the above dll's and see if it come back the correct rendering.

**Comment by fl82** [comment] 2021-01-10 15:57
I tried also in the same directory (not reinstalling the game but not modifying any settings or cam_ext, using again the official v0.2.1 old release and it renders ok again but not with the experimental it seems.

Old official release v0.2.1:

![Room_v021versionDLL](https://user-images.githubusercontent.com/76397937/104127875-d88ebc00-5364-11eb-9c0b-d4c7b4af7779.jpg)

![External_v021versionDLL](https://user-images.githubusercontent.com/76397937/104127882-e17f8d80-5364-11eb-94c6-5aaafcb48097.jpg)

**Comment by narzoul** [comment] 2021-01-10 16:09
Ok, so since the last attached release (in the comments) was working, it definitely has something to do with one of the render state changing functions, just have to figure out which one. From the logs, my first guess is pfnSetVertexShaderDecl, which is always called by the runtime after pfnSetStreamSource. If your driver resets the vertex shader declaration after changing stream sources, that would explain the malformed polygons.

Here's a version with pfnSetVertexShaderDecl removed from state caching: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5792875/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5792880/diff.txt) on top of 4370990)

**Comment by fl82** [comment] 2021-01-10 16:16
Tried the above attached dll with no pfnSetVertexShader and as before same rendering result:

![Room_no_pfnSetVertexShader](https://user-images.githubusercontent.com/76397937/104128389-92872780-5367-11eb-8ab9-b2f9bef9fe04.jpg)

**Comment by narzoul** [comment] 2021-01-10 17:14
Sorry, this is going to be a bit of a grind. I compiled 10 different versions here, to test each of the potential state changing functions that could break things. The diffs are in the attachment, but basically all I did in each case was that I replaced the other 9 functions' macros with FLUSH_PRIMITIVES instead of SET_DEVICE_STATE_FUNC, so that only that one remaining function will be cached.

Please let me know which of them have any glitches. All of them are in this zip: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5792979/ddraw.zip)

**Comment by fl82** [comment] 2021-01-10 17:54
I tried them all and **only one** has the known problems I attach the screenshot of the first mansion room of and it's the dll into the pfnSetRenderState test. 

![Room_pfnSetRenderState](https://user-images.githubusercontent.com/76397937/104131201-46db7a80-5375-11eb-9ff3-61f600d217e7.jpg)

**Comment by fl82** [comment] 2021-01-10 18:19
Meanwhile I'd like to ask you a curiosity that is not related to ddraw.dll and about what happens with this game using the d3d_display line and basically the D3D9 renderer as you can see in the patch, the D3DX9_43.dll file I suppose.
My iGPU (GMA3600/SGX545 core) was a native Directx9.0c/10 low power gpu with 400Mhz core and many "high end" features for netbook of those times but at the end had problems with speed, drivers and compatibility. Anyway should make this game to fly considering how old it is. If I use the D3D9 renderer at first the videos and menu this happens:

![menu](https://user-images.githubusercontent.com/76397937/104131648-fe718c00-5377-11eb-9d14-1d074a40b464.jpg)

And if I randomly get to start the 3D rendering game, at first it seems to render ok at really really fast frame rate with no gfx error but after few seconds it hangs for few seconds than unlock itself depending on the complexity of the scene (for example if the player looks to the floor only it seems to come back to the rendering if the scene is complex it stops for seconds and unlock and the stops and then unlock an so on.
Starting from the menu, I understand that Diretcx9 draw the DirectDraw menu using some 3D function to compensate it that probably my iGPU drivers can't support. How could I solve that for start if you know about Directx9 differences?

**Comment by narzoul** [comment] 2021-01-10 21:32
It's a little strange that pfnSetRenderState is causing the issues. During the 3D part of the game, that function isn't actually affected by the caching at all. So maybe some render state breaks during the transition to 3D and remains stuck in the wrong state.

I noticed from the logs that the game creates 2 Direct3D devices. The second one is created during the transition, so maybe some state is not reset properly there.
Here's a possible fix that clears the full state cache whenever the render target changes: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5793303/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5793304/diff.txt))

Direct3D 8 and newer are completely separate interfaces, independent of DirectDraw, which is why they're not supported by DDrawCompat. Most of the 2D stuff that was earlier provided by DirectDraw was removed from them, and some of it was moved to new APIs. As far as I know, the proper way to render 2D in Direct3D 8/9 is just to render textured rectangles in 3D (think of it like rendering a wall close the camera).

It is best to ask the developers of the engine for T2Fix to look at those menu issues and freezes. They have access to the source code and know how it works. For everyone else it's a much more difficult task.

If you still want to give it a shot, I'd recommend trying out apitrace: https://apitrace.github.io/
It's a very powerful tool for capturing traces of many different graphic APIs, and also supports Direct3D 9. There is plenty of info on the home page, but basically you can download the 32 bit Windows binaries, copy the lib\d3d9.dll to your Thief 2 install directory and run the game. It'll collect the trace to Thief2.trace on your desktop, which you can then open with bin\qapitrace.exe. It can even replay the trace and display what those API calls should render on your screen. Apparently you can even edit the calls.

**Comment by fl82** [comment] 2021-01-11 10:16
I tried the attached dll above and still the same problem of the pfnSetRenderState version:

![Room_clearcache_mod](https://user-images.githubusercontent.com/76397937/104167827-4f779380-53fd-11eb-9b56-d37bb8e94749.jpg)

Regarding the Directx9, thanks for the hints I'll try to understand those problems even if I've limits understanding things at this code level but still it's an opportunity to know more about how things works. I could use older more compatible system or modern faster one but I've got this mini-itx board into a mini-itx case and it's still an interesting x64/x86 config that I always thought was not pushed as fast it could and most of all the GPU.

**Comment by narzoul** [comment] 2021-01-11 11:11
Ok, let's take a step back and double check that really only pfnSetRenderState causes problems. This patch removes only this function from caching: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5795343/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5795345/diff.txt) on top of 4370990)

If there are no glitches with this, then we're gonna have to narrow down which particular render states cause the problem. There are dozens of them...

**Comment by narzoul** [comment] 2021-01-11 11:41
I may have accidentally attached the wrong build in the previous comment. I updated it now, just in case. Please redownload it if you already got it.

**Comment by fl82** [comment] 2021-01-11 12:34
I tried the latest attached above dll and it works, no gfx error.

**Comment by narzoul** [comment] 2021-01-11 19:15
Here's the next puzzle: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5797794/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5797795/diff.txt) on top of 4370990)

The zip now contains a renderstates.txt file too. Please copy this also to the Thief 2 install directory.

It has a bunch of numbers in it. Each one of them is an index of one of the render states that pfnSetRenderState can modify.
The ones that are listed in the file are not going to be cached by DDrawCompat. By default, it contains all render states, so running the game with it should produce no graphics errors (please verify that). Removing all numbers should reproduce the usual glitches.

The goal is to reduce the file contents to the minimum set of render states that need to be kept there to avoid glitches.
Please note that the file can only contain numbers and whitespaces (empty lines are ok).

Since there are 107 entries, testing them one by one would take a while. I'd recommend trying a faster strategy. For example, move half of the entries to a second file and run a test with the remaining entries. If there are no graphics errors, then you can delete the contents of the second file and continue by moving half of the remaining entries to the second file again. If there are graphics errors, then you moved one or more of the needed render states, so you should try to figure which ones are those by moving again half back to renderstates.txt, etc. On each successful test, everything in the second file can be deleted.

**Comment by narzoul** [comment] 2021-01-11 19:59
I've played around a bit with apitrace in the meantime, so here are some further tips.

If you double click a function call in the trace, a pane will open on the right side with some info about the state of the rendering just after that call. (You can also double click the frame header, which I assume shows the state after the last call in that frame). On the bottom of the pane, switch to the "Current State" tab, then select the "Surfaces" tab at the top. Here you will see thumbnails of the currently used textures and framebuffers. You can double clock the thumbnails to show the full sized image.

Generally, you should expect the RENDER_TARGET_0 framebuffer to container what will be displayed on your screen, and most probably it will only be updated by the IDirect3DDevice9::DrawPrimitiveUP calls (towards the bottom of each frame except the first), so try double clicking those calls. The PS_RESOURCE_0_LEVEL_0 texture should show a 640x480 image of the main menu. The RENDER_TARGET_0 framebuffer should simply be a scaled up version of the same (1024x768). I assume this is what gets corrupted in your case, while the texture should contain the correct image (I think the texture is generated in software, without using the GPU).

For me, frame 1 has solid white texture with solid black framebuffer.
Frame 2 has the background of the main menu without any text in both.
Frame 3 also has the text and the mouse cursor in both.
The rest continues in the same way, tracking the mouse cursor movement.

**Comment by fl82** [comment] 2021-01-11 20:52
Ok, I'll update as soon as finished the test.

For the D3D9 trace, in my early frames there's a complete no-sense of pixels/rectangles and portion of the main menu colors or the Win GUI (for example the numbers of the right angle date/time multiplied as in many tiles since the Frame 1. The Frame 0 is completely black. But the first strange thing I notice is that every time I double click on the initial frames for example, each double click from the frame 1 the frame 5 (ex.) produce a different image that is a as said sometime line, the "2021" of the time/date/font/background color of the right angle multiplied for all the frame,  for example:

![Example_frame](https://user-images.githubusercontent.com/76397937/104236353-b6756680-5456-11eb-8aa7-ab3268200af7.jpg)

![Frame1_gfxproblems](https://user-images.githubusercontent.com/76397937/104236634-297edd00-5457-11eb-9291-ad0f7e47b9b3.jpg)

**Comment by narzoul** [comment] 2021-01-11 20:59
What if you double click on the IDirect3DDevice9::SetTexture calls? Is the PS_RESOURCE_0_LEVEL_0 texture corrupted in those too, and randomly changing even in the same frame?

**Comment by fl82** [comment] 2021-01-11 21:11
Interesting, in the frame 1 the SetTexture call open as PS_RESOURCE a clean grey and white square image (_but I suppose is trasparent or white or empty_) and the frame buffer is black. In the frame 2 the SetTexture call open as frame buffer a confused rendering as usual, but the PS_RESOURCE image is definetely the game main menu background image as supposed to be.
Here's the frame buffer anyway is this:

![Frame2_framebuffer_setTexture](https://user-images.githubusercontent.com/76397937/104238819-ce021e80-5459-11eb-9df5-fa8e704bc48b.jpg)

**Comment by narzoul** [comment] 2021-01-11 21:15
I didn't think it was possible, but apparently you can play back the trace even on a different GPU. I just tried playing back a trace on my Intel HD GPU that was captured on my AMD GPU, and the frames are produced correctly.
Can you send me your trace file? I can take a quick look at it.

**Comment by fl82** [comment] 2021-01-11 21:30
Each time I double click on SetTexture the frame buffer still change every time.. 
Here's the trace:
[Thief2 Menu Frames](https://github.com/narzoul/DDrawCompat/files/5798432/Thief2_frames_Menu.zip)

**Comment by narzoul** [comment] 2021-01-11 22:08
Interesting, your trace renders correctly on my end. I think it's DrawPrimitiveUP call which somehow does the rendering incorrectly for you, maybe it uses the wrong texture (or wrong part of the "video memory") as input.

What happens if you double click on the DrawPrimitiveUP calls in frame 1 and frame 2?
The texture should be empty (transparent) in frame 1 and should show the menu background in frame 2.
I assume RENDER_TARGET_0 shows garbage in both frames for you, correct?

Try editing both of those calls (right click -> Edit), and change the PrimitiveCount to 1 in each. Then double click each of them again, does it change the results in RENDER_TARGET_0? It should only render into the top right triangle now. If that bottom left triangle remains black, then it's only the texturing/rasterizing part that's buggy. I wonder why it works correctly in the 3D parts of the game.

**Comment by fl82** [comment] 2021-01-11 23:00
Exactly, both frames RENDER_TARGET show usual confused pixel result. I edited both PrimitiveCount from 2 before to 1 now and double clicked again, shows always random confusing pixel but most of the rendered image is black with some triangles having those confused pixels  at the borders in RENDER_TARGET_0.

![PrimitiveCount_1](https://user-images.githubusercontent.com/76397937/104247671-8636c380-5468-11eb-90b8-7d3589f908c2.jpg)

Meanwhile on the other side I did some initial test for the legacy DDrawCompat and already discovered that: 1) with the complete txt file with all the number it works ok 2) it can work even with **only the 129 value** in the renderstates.txt. It's still early to say but it looks like one if not the only one that works but I'll do more test. Most seems to break as usual. But might the ddraw.dll need in other moments some of the others values? I can't see any gfx errors with just the 129 value but I wonder if the others values might be needed in other moments?

**Comment by narzoul** [comment] 2021-01-11 23:12
129 makes no sense to me. It's D3DDDIRS_WRAP1. There are also D3DDDIRS_WRAP0 through D3DDDIRS_WRAP7 that could be related then, but it's enough if you check the two neighbouring ones for now I think (128 and 130), with just that one number in the file in each case.

**Comment by fl82** [comment] 2021-01-11 23:19
With only 128 into renderstates.txt:
![Room_value128](https://user-images.githubusercontent.com/76397937/104249327-82587080-546b-11eb-8efb-4396763efc4d.jpg)

With only 130 value:

![Room_value130](https://user-images.githubusercontent.com/76397937/104249350-8d130580-546b-11eb-812b-0a42f42db833.jpg)

With only 129 value:
![Room_value129](https://user-images.githubusercontent.com/76397937/104249487-d2373780-546b-11eb-8970-347f1e679721.jpg)

**Comment by fl82** [comment] 2021-01-12 00:10
I am trying a lot of single value numbers into the txt files and until now I didn't find any other single value that can work alone for half the list. 
I tested also If I understood correctly that 128+129 works ok. Values 129+130 works ok too.

**Comment by narzoul** [comment] 2021-01-12 08:37
Ok, after some testing with the WRAPn render states, I have a theory of what the problem is.
In your log (and also mine), there are some strange values assigned to WRAP0:

```
0cb0 11:19:52.294       > _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,4294967294})
0cb0 11:19:52.294       < _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,4294967294}) = 0
0cb0 11:19:52.294       > _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,0})
0cb0 11:19:52.294       < _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,0}) = 0
0cb0 11:19:52.294       > _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,4294967292})
0cb0 11:19:52.294       < _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,4294967292}) = 0
0cb0 11:19:52.295       > _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,0})
0cb0 11:19:52.295       < _D3DDDI_DEVICEFUNCS::pfnSetRenderState(00D06F54, {D3DDDIRS_WRAP0,0}) = 0
```
The above values are 0xFFFFFFFE and 0xFFFFFFFC, i.e. all but the last 1 and 2 bits are set, respectively. According to the docs, only the 4 lowest bits have any meaning. It doesn't even make any sense, since the state is immediately reset to 0 afterwards, but I see the same behavior in other games too. These values are not set by the games, they seem to be coming internally from the Direct3D runtime.

I guess on your driver, the other bits (accidentally?) get assigned to the WRAP1 - WRAP7 render states, maybe because the driver stores them all in a single 32-bit value and some bitwise operation overwrites the higher bits too. But on both my AMD and Intel drivers, all but the 4 lowest bits are ignored.

So when I added the render state caching in DDrawCompat, these calls on your driver "corrupted" the WRAP1 - WRAP7 states too, which the cache didn't know about. When those states were reset to 0, the cache thought they were already at 0 and ignored those changes. The WRAP2 - WRAP7 states are not used by this game, so they don't cause further problems, but the WRAP1 corruption causes those strange shadows. I can now reproduce similar glitches when emulating this "overflow" in my drivers. Although in my case the glitches are along the polygon edges, and on your system it's not always the case, which I still don't understand.

I've added a small fix on top of the latest experimental version now, which discards all but the 4 lowest bits from these states, so hopefully the behavior will be identical on all drivers now: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/5800773/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/5800774/diff.txt))

**Comment by fl82** [comment] 2021-01-12 10:32
Very interesting! 
This gpu and driver always has been complicated for gaming (even retrogaming imho) and mostly for netbooks light usage; I always imagined that its core could've been originally oriented to smartphone (many Cortex A9 ARM SoC had the previous SGX535 core). The drivers were done _only_ for Win 7 32bit even if the cpu was already x64 and sort of works into Win 8.x 32bit system (they should be compatible to WDDM 1.1). It saw only few years of lifetime into the Atom system. Not to mention the linux story.

Anyway, to complete the previous dll test (even if I might not be sure 100%) all the other numbers tested if saved alone without any others in the renderingstate.txt, running the game showed the gfx artifacts. If used the original full list in renderingstates.txt and removed only the 129 value equally it shows the artifacts. If removed from the full list each 128 and 130 but leaving inside the 129 value, it works both times and as seen even with only that. :)

Now I try the latest experimental one. :-)

**Comment by fl82** [comment] 2021-01-12 11:00
Meanwhile to continue understanding also the D3D9 renderer problem I'll try to trace the part of the 3D rendering initial game even if it's difficult to arrive there with random mouse clicks for the menu problem. :-)

**Comment by narzoul** [comment] 2021-01-12 20:46
Added the fix to the latest experimental release. Thanks for the extensive testing!

**Closed by narzoul** 2021-01-12 20:46 UTC
