### ISSUE TITLE
[Project Visitor] Works different with different systems

### ISSUE THREAD

**Issue by WrathX** [narzoul/DDrawCompat#62] opened 2020-03-30 15:45 UTC
Hi Narzoul, I've appreciated all the work you've done with this. It's weird how your ddraw file works with the game I use it for (Project Visitor). I've helped many people get the game running using your ddraw but the thing is I have probably 8+ versions of your file from various dates in the past that I have to keep handy because it seems that even if two people have very similar systems, the same version of the ddraw file may make the game run differently. For some it locks their mouse up in certain menus, others the frame rates very from awesome to being super low (less that 10fps) and for some the game just crashes on launch. I'm just posting because I'm not sure if there would be anything you could think of that would be causing such random different things with different hardware. I know it's likely a tough one to answer but thought I would try asking at least. Thanks!

**Comment by narzoul** [comment] 2020-03-30 18:16
I can't really "guess" what's wrong without looking at logs. For the crashes, a core dump (and the debug logs) would be useful, along with the ddraw.dll that was used to produce it (unfortunately I don't have version info in the file yet).

The performance problems are a lot trickier, and pretty much impossible to debug remotely. The best we could try is checking debug logs from the ReleaseWithDebugLogs version to see if anything stands out, but for a 3D game this is likely to be gigantic (plus if the issue is sporadic, then it's much harder to see when it happens since the logging itself slows down the game significantly...)

Unfortunately this is a subscription-only game with no free demo or anything, and for obvious reasons I don't really wish to subscribe just to see if I can reproduce any of these issues.

**Comment by narzoul** [comment] 2020-03-30 18:42
One more thing that comes to mind: does it help to re-enable all CPU cores for the game? DDrawCompat disables all but the first core for compatibility reasons, but they can be re-enabled from the Task Manager while the game is running (right click on the process in the Details tab and select "Set affinity" from the popup menu).

**Comment by WrathX** [comment] 2020-03-30 18:59
Yea I totally understand about not having direct access to the game and trying to guess at things. I do appreciate the input and I'll see if any logs can be produced that would help. Also I didn't realize it disabled all but the first core. That's something else we can at least try on our end. If I can supply any additional info I'll can as soon as possible. Thanks again

**Comment by TheMartian** [comment] 2020-04-01 15:37
Hi Narzoul, if you are available and willing to take a look at things I would be happy to give you a free account, get you on our discord server and help you get setup so you can try some things out.  For crashing it either crashes immediately or it works.  For performance it varies wildly even with players that have the same video cards (and drivers sometimes).  I think others might even benefit from figuring some of this out since Project Visitor is such and old game, things discovered my apply to other games that use this ddraw.dll as well.  Please reach out to me and I can get you setup.  our main site is projectvisitor.com  thank you!

**Comment by narzoul** [comment] 2020-04-02 18:50
Thanks for the offer! I'll contact you when I have some time to look into this.

**Comment by narzoul** [comment] 2020-05-29 19:36
Are there still any graphics or performance issues with this game?

**Comment by TheMartian** [comment] 2020-05-29 20:26
So far it’s been really good, even I was able to use the latest build and it works fine.  Thanks for tracking down that mouse glitch!  Definitely fixed it :)

-M

**Comment by narzoul** [comment] 2020-05-29 20:50
Alright, then I'll close this for now. Feel free to reopen if you find other issues.

By the way, latest experimental release has some potentially significant 3D performance improvements for some games. As I see from some older debug logs of PV, it should affect this game also, so I'd recommend trying it out. Especially when using Intel graphics drivers, which I think benefits the most, and might even fix some crashes with that.

**Closed by narzoul** 2020-05-29 20:50 UTC
