### ISSUE TITLE
DDrawCompat v0.5.0 / v0.5.1 not working with Baldur's Gate 2

### ISSUE THREAD

**Issue by MacPaiva** [narzoul/DDrawCompat#280] opened 2024-01-11 20:34 UTC
Hi.

I was trying to use DDrawCompat v0.5.1 with Baldur's Gate 2 (without the 3d hardware acceleration) but unfortunately the screen keeps black while in fullscreen mode. In window mode the game gives an error.

This bug started with v0.5.0, since I tested with DDrawCompat v0.4.0 and it is OK.

Do you need any more info to help find de cause of the bug?

Thanks.

**Comment by MarkSpizu** [comment] 2024-02-18 18:49
v0.5.1 no longer supports many old games that used to work. Move on. Get over it!

**Comment by narzoul** [comment] 2024-03-17 10:26
I can't reproduce the issue. Please upload debug logs (set LogLevel=debug in DDrawCompat.ini).

**Comment by narzoul** [comment] 2024-04-21 21:56
Any updates on this? Is this still an issue with v0.5.2? If yes, please provide the logs as requested earlier.

**Comment by MacPaiva** [comment] 2024-04-22 15:06
Hi. First I would like to apologize for the delay sending the log. Here's the log of both 0.5.1 and 0.5.2. While the 0.5.1 the screen gets all black, the 0.5.2 the game closes itself.

[DDrawCompat-BGMain-debug_0.5.1.log](https://github.com/narzoul/DDrawCompat/files/15064952/DDrawCompat-BGMain-debug_0.5.1.log)
[DDrawCompat-BGMain-debug_0.5.2.log](https://github.com/narzoul/DDrawCompat/files/15064953/DDrawCompat-BGMain-debug_0.5.2.log)

**Comment by narzoul** [comment] 2024-04-22 17:15
That looks odd. There is no display driver loaded according to your logs. I can reproduce the issue by hooking the appropriate query to return an empty string instead of the name of the user mode driver dll, but doing the same with v0.4.0 produces also only a black screen, so I'm not sure what is going on here.

When you use v0.4.0, do you have a "Hooking user mode display driver" line in your log? What does the full line say? If it's not there either, then there seems to be something wrong or unusual about your drivers. What kind of GPU do you have?

**Comment by MacPaiva** [comment] 2024-04-22 18:43
It started on the v0.4.0-65-g3b8ff67c commit.

**Comment by narzoul** [comment] 2024-04-22 19:21
In your registry, is there an EmulationOnly key under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DirectDraw or HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\DirectDraw? What is the type and value? If the value is 1, try changing it to 0.

DDrawCompat doesn't work without DirectDraw hardware acceleration, which EmulationOnly=1 disables. This key should be automatically blocked (and it apparently is still correctly blocked on my end), but for some reason the RegQueryValueExA call for that particular key doesn't even show up in your debug logs.

**Comment by MacPaiva** [comment] 2024-04-22 19:29
I does not have the key on both folders.

**Comment by narzoul** [comment] 2024-04-22 19:56
Ah, I got it. It has to be the ForceDirectDrawEmulation shim. It installs an IAT hook in ddraw.dll and inserts its own virtual EmulationOnly key, bypassing the hook installed by DDrawCompat. I haven't tested that shim in a long time, but I can reproduce the issue with it now.

This should work: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/15068013/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/15068014/diff.txt) compared to v0.5.2)

**Comment by MacPaiva** [comment] 2024-04-22 20:04
It works! Glad I could help you fix this bug. Thanks for the great job with this wrapper!

**Comment by narzoul** [comment] 2024-04-22 20:05
Great, thanks for the report and helping to investigate! I'll add the fix to the next release.

**Comment by narzoul** [comment] 2024-07-02 23:01
Fixed in v0.5.3.

**Closed by narzoul** 2024-07-02 23:01 UTC
