### ISSUE TITLE
No Fog Effect in Combat Mission

### ISSUE THREAD

**Issue by Atomiser** [narzoul/DDrawCompat#20] opened 2017-08-19 23:38 UTC
Hi

I've been using this great app to good effect in Combat Mission (Beyond Overlord & Barbarossa to Berlin), thank you very much indeed. Stutter / lag in menus and in-game is completely eliminated. 

However all fog effects are not visible at all! :(

Is there any way for DDrawCompat to enable this please?

By way of further explanation: Scenarios are created with weather effects, fog being one of them (it's not compulsory of course), and can be set to either 'Fog, or Heavy Fog'. Fog effects were generated using pixel Fog Tables. If a scenario does contain fog, then in-game it can be seen by using Shift-W, to toggle between, None, Partial, and Full.

The old RivaTuner was able to expose this effect to older drivers with an optional 'Enable Fog Table emulation' setting.

Later drivers appear to have no way of setting the Fog Table effect on/off. This seems to have been replaced with vertex generated fog and expects games to use those Direct 3D calls instead. :(

This is a widely known problem, often reported on the Battlefront.com forums and nobody has ever managed to find a solution to this so far, other than use a really old graphics card and its associated driver. Arghh.

Here's hoping you can help Narzoul? Please! :)

My system is: Win 10 X64, I5-4690K @3.5GHz, Nvidia GTX-750Ti, 16 GB RAM, Asus Z97-Pro Gamer MB.

I have tried Win 8.1 also, with no difference.

Thank you.

**Comment by narzoul** [comment] 2017-08-20 19:37
I don't have an NVIDIA test system at the moment, so I'd like to request some additional info from you, if possible. I've seen a lot of people claiming that pixel fog (table fog) is no longer supported by NVIDIA drivers. I'd like you to check this on your system by using some tools available in the DirectX 7 SDK. Unfortunately it's no longer officially available for download anywhere as far as I know, but this link appears to work for example (check for viruses though): http://www.tdxlibrary.org/Downloads/Microsoft/dx7sdk.zip

Run the bin\DXUtils\DXCapsViewer.exe tool. Go to the View menu and click on the "All caps" option. Select the "Direct3D devices" label in the tree view, then go to the File menu and click on "Print subtree to file". This will produce a dxview.log file in the same directory, upload it here please.

Next, run the samples\Multimedia\D3DIM\bin\mfcfog.exe program. Click on the "Pixel (table) fog" radio button and adjust the "End:" range slider under "Fog parameters" closer to the minimal value. If you reduce it to minimum the test view should be completely obscured, and moving it farther should produce less fog. Is this the case? Also check the label below the fog type, does it say "Device using W-fog" or "Device using Z-fog"?

**Comment by Atomiser** [comment] 2017-08-20 19:52
Hi Narzoul :)

Here's the file you requested. I did a search and can see indeed that Fogtable has a YES against it. :)

So Nvidia are just not allowing us to get at it then?

Yes, the mcfog.exe works. When the slider is reduced the display is obscured until only the background is displayed using Pixel Fog or Vertex fog. 

It says using W-fog.

Hope this helps?

BTW, I found out yesterday, that the Radeon 7950 which obviously isn't Nvidia, but about the same age as a GTX 750 does allow fog effects to be seen in the game. So, AMD apparently reversed the decision to deny users access to Pixel Fog. That doesn't help us poor Nvidia users of course. ;)

[dxview.zip](https://github.com/narzoul/DDrawCompat/files/1237314/dxview.zip)

**Comment by narzoul** [comment] 2017-08-20 20:05
Yes, the caps look fine (same as on my AMD) assuming they're not lying. But the fact that it also works with the sample and with W-fog seems to suggest that it's properly hardware accelerated (as far as I know the software emulation built into Direct3D only supports Z-fog).

Yes, with AMD, fog works even natively in the game. But it's not the case with my Intel HD either, even though it also passes the sample test and supports W-fog based on the caps. I already found the issue with that one: it uses Z-coordinates when interpreting the fog range even though the game supplies it with W-coordinates. I found the root cause for this based on an older forum discussion for dgVoodoo2: the game doesn't set the projection matrix, and the fog really shouldn't work with the default matrix. However some drivers (AMD) seem to not enforce this and work anyway.

This is relatively easy to fix and I have a working hack for Intel already. I'll try to polish it up tomorrow and release a new experimental version for testing. With any luck, NVIDIA has the same issue.

**Comment by Atomiser** [comment] 2017-08-20 20:15
Well, that's great to hear you understand the problem and know how to fix it. :)

Incidentally, I have tried DgVoodoo2 also with this game and had no luck either, so I did ask on the forum thread for it if it could be fixed, but, it appeared that the author didn't know what the problem was.

So, very pleased you were able to immediately get to the root of this. If this works you'll be a hero on the Battlefront.com forums I would imagine. ;)

Well, I look forward to testing your experimental release. 

Until then, thank you for your time and effort.

**Comment by narzoul** [comment] 2017-08-21 20:38
I digged a bit deeper and I think I found the right driver call to modify - at least fog works for me now on Intel HD 4600. More technical details are in the commit message.

I have no idea whether this fix works with NVIDIA. Please try the latest experimental release and let me know the results.

**Comment by Atomiser** [comment] 2017-08-21 21:19
Hi Narzoul.

Just tried the experimental .xip, and... I can see fog now, for the first time _ever_, in both CMBO and CMBB. :)

I tried the Shift-W weather toggle, but see no difference between partial and full (or extreme in CMBB), but the 'full' / 'extreme' settings could be for showing more dense rain/snow effects possibly? But, setting it to none, turns the fog effect off completely, and boy, what a difference it makes. So much more realistic now with fog set to 'on' in maps that use it!

With pre-set scenarios and the battle generator, you can easily see the difference between a map set to 'fog' vs one set to 'heavy fog'. Visibility is severely reduced in the latter.

Just one question I have. I am seeing horizontal 'banding' as I scroll over the map while the fog effect is on. It's more noticable as you scroll past the edges of the map. Do you also see that effect on the Intel HD graphics?

It's no big deal really. Most likely a limitation of what was possible then using pixel fog perhaps? Never having seen fog before in the game, I have nothing to compare against, so not sure if it's 'correct' or not.

Anyway, excellent job mate! Well done, and thank you very much.

Let me know if you need any more testing done. I'll be happy to help out.

**Comment by narzoul** [comment] 2017-08-21 22:14
Looks like it's related to dithering support for 16-bit color mode. Banding is visible for me on AMD, but not on Intel HD, even though both report dithering as supported. I tried forcing it on/off in the driver render states but it only affects Intel, in that it can be forced off and then it has the same banding.
Based on what I read elsewhere too, unfortunately I think most AMD/NVIDIA GPUs don't actually support dithering.

An alternative solution would be using a 32-bit display mode, but I don't know if the game supports that. It could be forced, but I don't plan on implementing that as an option anytime soon. I think dgVoodoo2 already supports that though, so once the fog issue is fixed there maybe that could be an alternative. Or you could use your Intel HD GPU too?

**Comment by narzoul** [comment] 2022-09-27 21:33
I've added a RenderColorDepth setting in v0.4.0, which can solve the color banding.

**Closed by narzoul** 2022-09-27 21:33 UTC
