### ISSUE TITLE
Webpage doesnt work inside the game

### ISSUE THREAD

**Issue by jcgo16** [narzoul/DDrawCompat#9] opened 2017-01-02 17:51 UTC
I have a game called O2JAM INT
when i replaced the ddraw.dll inside the game, game pages doesn't work anymore

i know that the page is loaded because i can hover it, but it doesn't show up

System:

Intel i7-6700k
Nvidia GTX 970 4GB
Windows 10 Pro

**Comment by narzoul** [comment] 2017-01-04 21:13
I took a quick look. I'm not sure which pages you mean, but I do see a problem e.g. with the user list on the right side right after logging in to a server. It is mostly invisible with DDrawCompat, though sometimes a flicker of it can be seen when moving the mouse. I assume other pages might have similar issues.

Now, from a technical point of view, this game is rather strange. The system requirements claim it needs Windows Vista or newer, yet it still uses DirectDraw? What makes it worse, it seems to mix in some GDI as well.

The OS requirements lead me to believe this game was written with desktop composition in mind, so it probably wouldn't work well (at least the GDI parts) with desktop composition turned off. Unfortunately this can't be tested on Windows 10 (can't turn off composition anymore), but I'll try to confirm it on Windows 7 over the weekend when I'll hopefully have access to such a system.

The problem is that DDrawCompat expects exactly the opposite since most (I thought all...) DirectDraw games were written for Windows XP and earlier systems where desktop composition wasn't available and GDI was handled very differently. And this earlier behavior is exactly what DDrawCompat tries to emulate for Vista and above, which won't work for a game written specifically for desktop composition.

Now all is not lost however, because disabling the GDI emulation in DDrawCompat, along with the "DXPrimaryEmulation -DisableMaxWindowedMode" compatibility shim that it forces on by default is probably all that is needed to get this game to run properly, and indeed some quick tests with this look promising. The problem is that this could only be properly added via configuration options, which is a feature I haven't got around to adding yet and could still be a few more months till I do.

There are two things I can offer in the meantime:

1. If you only need DDrawCompat because of performance issues (I noticed some stuttering even in some of the menus without DDrawCompat), then you can probably fix that using Compatibility Administrator (32-bit) alone. You have to add the "Disable8And16BitD3D" compatibility mode to OTwo.exe.
If you don't know your way around the Compatibility Administrator tool, you can also use this attached [o2jamfix.zip](https://github.com/narzoul/DDrawCompat/files/685891/o2jamfix.zip) file, which contains the same fix exported from the tool. Extract it somewhere and use the install/uninstall scripts that I've included to add or remove the fix.
You will also have to remove or rename the ddraw.dll file included with the game (and don't use DDrawCompat either).

2. If the above fails and/or you still need DDrawCompat for other reasons, I can offer to make those minimal changes I mentioned earlier on top of some stable version (v.0.2.1 probably) and create a special purpose release as an attachment here (at least until I make a "proper" fix via config options).

**Comment by jcgo16** [comment] 2017-01-05 07:27
ok i did the 1st one but its showing the pink stuff, dont worry about the game requirements, im the one who did it, but... the game was made way before where 98 and xp are the latest operating system

so yeah its showing the pink stuff

**Comment by jcgo16** [comment] 2017-01-05 07:28
the above did fix the laggy stuff, but.. the color is wrong and pinky

**Comment by jcgo16** [comment] 2017-01-05 07:32
btw im willing to contribute and donate to you if you can fix it

**Comment by narzoul** [comment] 2017-01-05 20:03
Ok, plan B then. Here's the v0.2.1 release with disabled GDI emulation and no DXPrimaryEmulation shim: 
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/688216/ddraw.zip)

Before using this fix, please first uninstall the compatibility fix I attached in my previous message (o2jamfix.zip).

I have removed exactly the following (non-consecutive) lines from DllMain.cpp to compile this release:
`Compat::Log() << "Installing GDI hooks";`
`CompatGdi::installHooks();`
`setAppCompatData(disableMaxWindowedMode, 0);`
`CompatGdi::uninstallHooks();`

**Comment by jcgo16** [comment] 2017-01-05 21:59
Im gonna look at it later when i get home, thank you

**Comment by jcgo16** [comment] 2017-01-06 03:01
is there anything i need to know about compatibility?

**Comment by jcgo16** [comment] 2017-01-06 07:27
Is it possible too, to add window mode?

**Comment by narzoul** [comment] 2017-01-06 20:43
There's no need to repay me. I also don't accept donations, though thank you for the offer.

About compatibility: I think this workaround should be fine for Windows Vista, 7 and 10.
Windows 8 might still have some performance issues, as I remember (when I still had Win 8) most old games needed either the DXPrimaryEmulation or NoGDIHWAcceleration shim to have good performance. DXPrimaryEmulation can't be used because that would definitely make the GDI parts invisible. NoGDIHWAcceleration should be fine though, if it's needed.

Here's an update of the Compatibility Fix I posted earlier, but now it contains only the NoGDIHWAcceleration shim: [o2jamfix.zip](https://github.com/narzoul/DDrawCompat/files/690763/o2jamfix.zip)
It's unnecessary for Win Vista and 7 (and may not even be supported there). It may or may not be needed for good performance on Win 8, and it probably makes no difference on Win 10 (it doesn't on my system).

Windowed mode is unlikely to be added to DDrawCompat in the near future. It would be a very complex feature, especially for a game like this that mixes DirectDraw and GDI. It may happen someday in the distant future, but for now compatibility takes precedence and there's still plenty of work to do on that front.

Your best bet for a working windowed mode would be [DxWnd](https://sourceforge.net/projects/dxwnd/). It has an overwhelmingly lot of config options to set up games properly, but you can ask for help from the developer on the Discussion page (forum) if you're having trouble with that.

And by the way, I managed to run some tests on Windows 7 now and the game works fine there even with desktop composition disabled. So more than likely there's an issue in DDrawCompat's GDI emulation, which I may be able to fix in the future without having to add any config options. I'll keep this issue open until then.

**Comment by jcgo16** [comment] 2017-01-07 02:53
btw whats inside those sdb?

**Comment by narzoul** [comment] 2017-01-07 09:26
The first one contains the Disable8And16BitD3D shim, the second one contains NoGDIHWAcceleration. In both cases it's set to match OTwo.exe. You can check it yourself using the Microsoft Application Compatibility Toolkit, which on Windows 10 is part of the [Windows Assessment and Deployment Kit (ADK)](https://developer.microsoft.com/en-us/windows/hardware/windows-assessment-deployment-kit). You should uncheck all the other tools in the web installer, otherwise it can be a huge download.

**Comment by jcgo16** [comment] 2017-01-07 17:19
alright thank you

**Comment by jcgo16** [comment] 2017-01-14 18:14
some people having this problem

7100 14:09:49.631 Process path: C:\Program Files (x86)\O2JAM INT\otwo.exe
7100 14:09:49.631 Loading DDrawCompat from C:\Program Files (x86)\O2JAM INT\DDRAW.dll
7100 14:09:49.631 DDrawCompat loaded successfully
7100 14:09:50.086 Installing DirectDraw hooks
7100 14:09:50.112 Installing registry hooks
7100 14:09:50.113 Finished installing hooks
7100 14:09:50.125 Failed to find the requested display mode: 800x600x16
7100 14:09:51.328 Detaching DDrawCompat
7100 14:09:51.328 DDrawCompat detached successfully
this error was fixed with 16BITCOLOR compatibility setting

and others experiencing black screen but no error log

**Comment by jcgo16** [comment] 2017-01-14 18:26
ok now i know, some people experiencing blank screen when the game is not set in 8bit color mode

so weird, some people only need 16bit

any ideas?

**Comment by narzoul** [comment] 2017-01-14 20:40
The missing 16 bit color mode can probably be fixed, it's already planned for another issue as well.

The blank screen I don't know about, and it's unlikely I can guess what's wrong without being able to reproduce it. Those people must have something in common, what OS and GPU do they use?
It may also be some software running in the background, especially overlays or video capture tools that could interfere. There are known issues with Fraps for example (blank screen is common).

**Comment by jcgo16** [comment] 2017-01-14 20:50
Windows 10, gtx 750ti

Hope to see the new update

**Comment by jcgo16** [comment] 2017-01-14 20:52
Yup when i see their systems there some overlays running like bandicam and frapsI did fix it by using 8bit color modeBut hope to see it fixed without using registry compat

**Comment by narzoul** [comment] 2017-07-03 21:57
The issues other than those related to overlays should be fixed in the latest experimental release. You should no longer need to use the 8 or 16 bit color mode compatibility setting or the o2jamfix.zip I posted as a workaround earlier. Please try removing them both and check if this release alone works fine for you (when not using overlays).

**Comment by jcgo16** [comment] 2017-07-20 01:16
tried it, some people are experiencing lag and other related issues, ill try to dig on this because it may be the OS or the Graphics Settings

**Closed** 2020-12-15 09:14 UTC
