### ISSUE TITLE
Heavy flicker after alt-tabbing in NFS 2 and NFS High Stakes

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#316] opened 2024-05-20 18:49 UTC
Hello, was testing the latest version of DDrawCompat and decided to experiment with the alt-tab solutions for these two games.

From my testing with `keepvidmem(1)` set, both games present the same flickery behavior, but aside from that everything else seems to work like normal (no missing/glitchy textures etc).

As for it set to `(0)`, the dashboard of the car in NFS 2 (Software Renderer) turns completely black but goes back to normal once you switch views or pause/unpause the game. HS on the other hand black screens entirely with just the audio playing in the background.

OS: Windows 8.1
GPU: Intel iGPU
CPU: 3rd gen Celeron
[DDrawCompat-nfs2sen.log](https://github.com/narzoul/DDrawCompat/files/15380764/DDrawCompat-nfs2sen.log)
[DDrawCompat-nfs4.log](https://github.com/narzoul/DDrawCompat/files/15380765/DDrawCompat-nfs4.log)

**Comment by narzoul** [comment] 2024-05-22 20:37
The flickering is caused by a bug in the keepvidmem(1) setting. It doesn't keep the back buffers of the primary surface chain. This should fix that:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/15408483/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/15408486/diff.txt) compared to v0.5.2)

NFS 2 is software rendered as you mentioned, so keepvidmem won't help it, since none of those resources are stored in video memory. There is no difference between AltTabFix=off, keepvidmem(0) and keepvidmem(1) according to my testing (except for the above bug).

**Comment by narzoul** [comment] 2024-07-02 23:08
Fixed in v0.5.3.

**Closed** 2024-07-02 23:19 UTC
